package gregtech6.datagen;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import gregapi.oredict.OreDictPrefix;
import gregtech6.fluid.GTFluids;
import gregtech6.item.GT6Circuits;
import gregtech6.item.MaterialPrefixItem;
import gregtech6.jei.GT6JeiPlugin;
import gregtech6.registry.GT6Tools;
import gregtech6.registry.GTMaterialBlocks;
import gregtech6.registry.GTMaterialItems;
import gregtech6.registry.GTWires;
import net.minecraft.data.PackOutput;
import net.minecraftforge.common.data.LanguageProvider;

/**
 * zh_cn lang, the A-wave small-unit companion of {@link GT6EnUs} (task p20-i18n-zhcn-provider,
 * ADR 2026-09-06-p20-i18n-zhcn-pipeline): zh_cn.json is GENERATED by this provider — the
 * hand-written-JSON red line forbids editing it directly. The translation VALUES come from the
 * committed reference table {@code /gregtech6/lang/zh_cn_ref.tsv} (produced by
 * {@code mdk/tools/gen_zhcn_ref.py} from the GT6 1.7.10 zh lang dump + a hand-translation
 * layer); the lang KEYS are derived here with the same single
 * {@link MaterialPrefixItem#snakeCase} implementation the en provider uses, so no second
 * snake_case algorithm exists (the Python side of the pipeline deliberately carries zero key
 * logic, ADR §1.1).
 *
 * <p>Four small-unit walks over the same registry sources as {@link GT6EnUs} — three mirror the
 * en walk, the material walk consumes GT6EnUs's shared seam directly (per-key English fallback
 * for skipped rows is vanilla's built-in bilingual chain — LanguageManager.java:50-52 +
 * ClientLanguage.java:29-46 — so zero fallback code lives here):
 * <ol>
 * <li>{@link #addTabTitles()} — the creative tab titles: item prefix tabs
 *     ({@code itemGroup.gt6.<snake>} over {@link GTMaterialItems#tabPrefixes()}), block prefix
 *     tabs (over {@link GTMaterialBlocks#tabPrefixes()}) and the special MTE-category tabs,
 *     joined against the dump's {@code itemGroup.<camel>} family or the hand rows;</li>
 * <li>{@link #addPrefixTemplates()} — the {@code gt6.tagprefix.<snake>} display templates.
 *     The en provider emits all 467 OP prefixes; zh emits ONLY the hand-translated in-use set
 *     (status=hand direct rows, ADR §1.2 — the dump has no authoritative template face, and
 *     affix stripping would be statistical generalisation multiplied by 1273 materials). The
 *     parity test (GT6LangParityTest) structurally guarantees zh ⊆ en;</li>
 * <li>{@link #addMaterialNames()} — the {@code gt6.material.<snake>} small units, the shared
 *     {@link GT6EnUs#materialWalkEmittedKeys} seam (alias merge, first mID wins) joined against
 *     the dump's {@code gt.material.<Pascal>} family (the Map form carries the merged material
 *     identity the TSV family join needs — task p21-i18n-walk-seam-normalize);</li>
 * <li>{@link #addMiscUnits()} — the atomic misc keys (tools, the eight atomic covers, the
 *     circuit selector tag + its configuration tooltip, the JEI coke-oven info page, the
 *     example chest, the two port fluids). The COMPOSED domains became B-wave template keys
 *     (p20-i18n-compose-wires/-rows); B1's face is {@link #addWireDomainUnits()} and B2's faces are
     *     {@link #addStoneVariantUnits()} + {@link #addRowDomainUnits()} — with the
     *     B-wave landed, the parity test's composed-domain negative assertions are
     *     EMPTY (the closeout state).
 * </ol>
 *
 * <p>Rows with status {@code review} (pure-ASCII dump values, suspected untranslated, e.g.
 * {@code gt.material.Magnite=Magnite}, tmp/gregtech.lang:5003) and rows with no reference
 * entry at all are skipped: the runtime falls back to English per key. The {@code mte} family
 * in the TSV is deliberately unused here — it is inert census data until the MTE ID-join
 * subface lands (arch card tasks.p20-arch-i18n).
 *
 * <p>Non-final on purpose: GT6LangParityTest records {@code add()} through a same-package
 * subclass (the GT6EnUsJeiInfoTest:52-64 posture) to collect both providers' key sets in a
 * bare JVM without a datagen run.
 */
public class GT6ZhCn extends LanguageProvider {

	/** Classpath location of the generated reference table (rides the jar, ADR §1.1). */
	static final String REFERENCE_RESOURCE = "/gregtech6/lang/zh_cn_ref.tsv";

	/** One reference row: the translation value and its pipeline status. */
	record RefRow(String value, String status) {
		/** review rows are suspected-untranslated dump entries — the provider skips them. */
		boolean skipped() {
			return "review".equals(status);
		}
	}

	private final Map<String, Map<String, RefRow>> reference;

	public GT6ZhCn(PackOutput output) {
		super(output, GT6DataGenerators.MOD_ID, "zh_cn");
		this.reference = loadReference();
	}

	@Override
	protected void addTranslations() {
		addTabTitles();
		addPrefixTemplates();
		addMaterialNames();
		addMiscUnits();
		addBackfillUnits();     // task p23-i18n-zh-442-backfill
		addWireDomainUnits();
		addStoneVariantUnits(); // task p20-i18n-compose-rows
		addRowDomainUnits();    // task p20-i18n-compose-rows
		addGrassUnits();        // task p24-grass-block
	}

	/**
	 * The grass family zh faces (task p24-grass-block, the GT6EnUs.addGrassBlocks mirror):
	 * the 6 variant display names (all "草方块" — the en "Grass" parity ruling, no colour
	 * prefix) + the 2 tooltip lines. All 8 ride the reference table's hand layer (direct
	 * rows; the tooltip zh face is the dump's {@code gt.grass.tooltip} wording,
	 * tmp/gregtech.lang:3228, plus a hand translation for the :3229 row the dump never
	 * translated).
	 */
	private void addGrassUnits() {
		for (String tPath : gregtech6.registry.GTGrassBlocks.PATHS) {
			addDirect("block.gt6." + tPath);
		}
		addDirect(gregtech6.block.GTGrassBlock.TOOLTIP_KEY);
		addDirect(gregtech6.block.GTGrassBlock.TOOLTIP_SPRAY_KEY);
	}

	/**
	 * The 442-key zh backfill (task p23-i18n-zh-442-backfill), non-tagprefix face: the 77
	 * atomic keys whose en counterpart is a whole-string {@code add} in {@link GT6EnUs} —
	 * the barrel/fluid-pipe/machine blocks, the fluid display names, the P22 spray-can
	 * items + tooltips, the five backfill materials (the dump rows are review/absent, so
	 * they cannot ride the {@link #addMaterialNames()} family join) and the two new tabs.
	 * (The 365 {@code gt6.tagprefix.*} keys need NO new walk here —
	 * {@link #addPrefixTemplates()} already walks every {@link OreDictPrefix#VALUES} key and
	 * only the reference-table hand rows were missing.) Every key mirrors an en literal and
	 * carries a hand row in the reference table; the wording evidence lives in the gen
	 * script's backfill tables.
	 */
	private void addBackfillUnits() {
		// blocks: barrels (Drum = 鼓), the wood barrel (dump MTE 6990 join), the machines,
		// the coke-oven multiblock pair, the two atomic legacy electric wires, the pipes
		addDirect("block.gt6.advanced_crafting_table"); // task p24-act-machine
		addDirect("block.gt6.barrel_adamantium");
		addDirect("block.gt6.barrel_awakened_draconium");
		addDirect("block.gt6.barrel_draconium");
		addDirect("block.gt6.barrel_gaia_spirit");
		addDirect("block.gt6.barrel_infinity");
		addDirect("block.gt6.barrel_logistics");
		addDirect("block.gt6.barrel_metal");
		addDirect("block.gt6.barrel_netherite");
		addDirect("block.gt6.barrel_plastic");
		addDirect("block.gt6.barrel_tantalum_hafnium_carbide");
		addDirect("block.gt6.barrel_titanium");
		addDirect("block.gt6.barrel_tungsten");
		addDirect("block.gt6.barrel_tungsten_alloy");
		addDirect("block.gt6.barrel_tungstensteel");
		addDirect("block.gt6.barrel_void_metal");
		addDirect("block.gt6.barrel_wood");
		addDirect("block.gt6.crank");
		addDirect("block.gt6.crusher");
		addDirect("block.gt6.energy_source");
		addDirect("block.gt6.lathe");
		addDirect("block.gt6.multiblock_coke_oven");
		addDirect("block.gt6.multiblock_coke_oven_bricks");
		addDirect("block.gt6.oven");
		addDirect("block.gt6.shredder");
		addDirect("block.gt6.wire_electric_1x");
		addDirect("block.gt6.wire_electric_2x");
		addDirect("block.gt6.wood_fluid_pipe_medium");
		addDirect("block.gt6.wood_fluid_pipe_small");
		// fluids: the 21 remaining display names (dump anchors 柴油/蒸馏水/幻露 per the research card)
		addDirect("fluid.gt6.cactuswater");
		addDirect("fluid.gt6.cold_water");
		addDirect("fluid.gt6.diesel");
		addDirect("fluid.gt6.distilled_water");
		addDirect("fluid.gt6.ethanol");
		addDirect("fluid.gt6.fuel");
		addDirect("fluid.gt6.hot_water");
		addDirect("fluid.gt6.jetfuel");
		addDirect("fluid.gt6.kerosine");
		addDirect("fluid.gt6.maplesap");
		addDirect("fluid.gt6.mnwtr");
		addDirect("fluid.gt6.nitrofuel");
		addDirect("fluid.gt6.petrol");
		addDirect("fluid.gt6.reedwater");
		addDirect("fluid.gt6.sap");
		addDirect("fluid.gt6.seawater");
		addDirect("fluid.gt6.spdew");
		addDirect("fluid.gt6.steam");
		addDirect("fluid.gt6.water_boiling");
		addDirect("fluid.gt6.water_geothermal");
		addDirect("fluid.gt6.waterdirty");
		// task p24-dye-chemical-fluids: the 16 dye-chemical display names + chlorine — the
		// dump carries all 17 faces (S:fluid.dye.chemical.* tmp/gregtech.lang:230-244,
		// S:fluid.chlorine=氯 :168); the keys ride the SAME GTFluids.dyeChemicalName
		// derivation the en walk and the FluidType descriptionIds use, so the two locale
		// faces cannot drift on the key side. Values are hand rows in the reference table.
		for (int i = 0; i < 16; i++) {
			addDirect("fluid.gt6." + GTFluids.dyeChemicalName(i));
		}
		addDirect("fluid.gt6.chlorine");
		// the P22 spray-can domain (no upstream face anywhere — all hand)
		addDirect("item.gt6.spray_can_empty");
		addDirect("item.gt6.spray_paint_black");
		addDirect("item.gt6.spray_paint_blue");
		addDirect("item.gt6.spray_paint_brown");
		addDirect("item.gt6.spray_paint_cyan");
		addDirect("item.gt6.spray_paint_gray");
		addDirect("item.gt6.spray_paint_green");
		addDirect("item.gt6.spray_paint_light_blue");
		addDirect("item.gt6.spray_paint_light_gray");
		addDirect("item.gt6.spray_paint_lime");
		addDirect("item.gt6.spray_paint_magenta");
		addDirect("item.gt6.spray_paint_orange");
		addDirect("item.gt6.spray_paint_pink");
		addDirect("item.gt6.spray_paint_purple");
		addDirect("item.gt6.spray_paint_red");
		addDirect("item.gt6.spray_paint_remover");
		addDirect("item.gt6.spray_paint_white");
		addDirect("item.gt6.spray_paint_yellow");
		addDirect("gt6.spraycan.decolor");
		addDirect("gt6.spraycan.paint");
		addDirect("gt6.spraycan.remaining");
		// the five backfill materials (review/absent dump rows cannot ride the family join;
		// superconductor = the TeamNED double-source cross)
		addDirect("gt6.material.breeze");
		addDirect("gt6.material.carminite");
		addDirect("gt6.material.fireleaf");
		addDirect("gt6.material.golden_amber");
		addDirect("gt6.material.superconductor");
		// the two new tabs
		addDirect("itemGroup.gt6.billet");
		addDirect("itemGroup.gt6.spray_cans");
	}

	/**
	 * The B2 stone-variant composed-display units (task p20-i18n-compose-rows): the 16
	 * {@code gt6.stone.variant.<snake>} position-param templates the
	 * {@code GTStoneBlock.getName} compose fills (the stone-name slot rides the
	 * gt6.material.* small units, zero new material debt). Wording = the dump's
	 * gt.stone.andesite.N family split (tmp/gregtech.lang:15246-15262).
	 */
	private void addStoneVariantUnits() {
		for (gregtech6.block.stone.StoneVariant tVariant : gregtech6.block.stone.StoneVariant.VALUES) {
			addDirect(tVariant.key());
		}
	}

	/**
	 * The B2 rows composed-display units (task p20-i18n-compose-rows): every family template
	 * + small unit the rows composes consume, walked from the SAME row tables and key
	 * derivations the en walk uses (the mirrors cannot drift on the KEY face; the VALUE face
	 * is the hand layer in the reference table). The atomic rows (brick burning box, heat
	 * transmitter, the two wood gearboxes) ride the same hand rows as their en literals.
	 */
	private void addRowDomainUnits() {
		// a word shared by several families is ONE unit key — dedup like the en walk's
		// addRowMatUnit (duplicate add would be a hard failure on the recording face)
		java.util.Set<String> tEmitted = new java.util.HashSet<>();
		
		addDirect(gregtech6.registry.GT6Kinetics.AXLE_DISPLAY_KEY);
		for (int tSize = 0; tSize < gregtech6.registry.GT6Kinetics.AXLE_SIZE_NAMES.length; tSize++) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Kinetics.axleSizeUnitKey(tSize));
		}
		for (gregtech6.registry.GT6Kinetics.AxleSpec tSpec : gregtech6.registry.GT6Kinetics.AXLE_SPECS) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Kinetics.axleMatUnitKey(tSpec));
		}
		// steam engines: the two templates + the row-material units
		addDirect(gregtech6.registry.GT6Kinetics.STEAM_DISPLAY_KEY);
		addDirect(gregtech6.registry.GT6Kinetics.STEAM_DISPLAY_STRONG_KEY);
		for (gregtech6.registry.GT6Kinetics.SteamEngineRow tRow : gregtech6.registry.GT6Kinetics.STEAM_ENGINES) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Kinetics.steamMatUnitKey(tRow));
		}
		// diesel: the template + the row-material units
		addDirect(gregtech6.registry.GT6Kinetics.DIESEL_DISPLAY_KEY);
		for (gregtech6.registry.GT6Kinetics.DieselSpec tSpec : gregtech6.registry.GT6Kinetics.DIESEL_SPECS) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Kinetics.dieselMatUnitKey(tSpec));
		}
		// burning boxes: the four templates + three family words + the row-material units
		addDirect(gregtech6.registry.GT6BurningBoxes.DISPLAY_KEY);
		addDirect(gregtech6.registry.GT6BurningBoxes.DISPLAY_DENSE_KEY);
		addDirect(gregtech6.registry.GT6BurningBoxes.DISPLAY_FLUIDBED_KEY);
		addDirect(gregtech6.registry.GT6BurningBoxes.DISPLAY_FLUIDBED_DENSE_KEY);
		addDirect(gregtech6.registry.GT6BurningBoxes.FAMILY_SOLID_UNIT_KEY);
		addDirect(gregtech6.registry.GT6BurningBoxes.FAMILY_LIQUID_UNIT_KEY);
		addDirect(gregtech6.registry.GT6BurningBoxes.FAMILY_GAS_UNIT_KEY);
		for (gregtech6.registry.GT6BurningBoxes.BurningBoxRow tRow : gregtech6.registry.GT6BurningBoxes.allRows()) {
			addRowUnit(tEmitted, gregtech6.registry.GT6BurningBoxes.matUnitKeyOf(tRow));
		}
		addDirect("block.gt6.brick_burning_box"); // the atomic Brick row (the whole-string key on both faces)
		// boilers: the two templates + the row-material units
		addDirect(gregtech6.registry.GT6Boilers.DISPLAY_KEY);
		addDirect(gregtech6.registry.GT6Boilers.DISPLAY_STRONG_KEY);
		for (gregtech6.registry.GT6Boilers.BoilerRow tRow : gregtech6.registry.GT6Boilers.allRows()) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Boilers.matUnitKeyOf(tRow));
		}
		// machine tiers: the template + three machine words + three ordinal units
		addDirect(gregtech6.registry.GTMachines.MACHINE_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_SHREDDER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_CRUSHER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_LATHE_UNIT_KEY);
		for (int tTier = 2; tTier <= 4; tTier++) {
			addDirect(gregtech6.registry.GTMachines.machineTierUnitKey(tTier));
		}
		// dryer/distillery: the two family templates + their row-material units
		addDirect(gregtech6.registry.GTMachines.DRYER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.DISTILLERY_DISPLAY_KEY);
		for (java.util.List<gregtech6.block.GTBasicMachineBlock.MachineRow> tRows
				: java.util.List.of(gregtech6.registry.GTMachines.DRYER_ROWS, gregtech6.registry.GTMachines.DISTILLERY_ROWS)) {
			for (gregtech6.block.GTBasicMachineBlock.MachineRow tRow : tRows) {
				addRowUnit(tEmitted, "gt6.row.mat." + tRow.matSlug());
			}
		}
		// canner (task p24-canner-machine): the family template + the VN voltage-row units
		addDirect(gregtech6.registry.GTMachines.CANNER_DISPLAY_KEY);
		for (gregtech6.block.GTBasicMachineBlock.MachineRow tRow : gregtech6.registry.GTMachines.CANNER_ROWS) {
			addRowUnit(tEmitted, "gt6.row.mat." + tRow.matSlug());
		}
		// large boiler + dense wall: the templates + the row-material units
		addDirect(gregtech6.registry.GTMultiBlocks.LARGE_BOILER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMultiBlocks.DENSE_WALL_DISPLAY_KEY);
		for (gregtech6.registry.GTMultiBlocks.LargeBoilerRow tRow : gregtech6.registry.GTMultiBlocks.LARGE_BOILER_ROWS) {
			addRowUnit(tEmitted, gregtech6.registry.GTMultiBlocks.boilerMatUnitKeyOf(tRow));
		}
		for (gregtech6.registry.GTMultiBlocks.MultiblockPartRow tRow : gregtech6.registry.GTMultiBlocks.WALL_ROWS) {
			addRowUnit(tEmitted, gregtech6.registry.GTMultiBlocks.wallMatUnitKeyOf(tRow));
		}
		addDirect("block.gt6.heat_transmitter"); // the atomic transmitter (the whole-string key)
		// lightning rod (task p24-lightning-rod): the controller + the three atomic parts +
		// the addToolTips replay keys (the dump rows :15141/:11359/:11380/:11389/:17758-17766,
		// the hand layer in the reference table; the KEY face mirrors the en addMultiBlocks tail)
		addDirect("block.gt6.multiblock_lightning_rod");
		addDirect("block.gt6.machine_wall_tungsten");
		addDirect("block.gt6.niobium_titanium_coil");
		addDirect("block.gt6.lightning_rod");
		addDirect(gregtech6.block.multiblock.GTLightningRodBlock.Item.KEY_STRUCTURE);
		for (int i = 1; i <= 9; i++) {
			addDirect(String.format(gregtech6.block.multiblock.GTLightningRodBlock.Item.KEY_LINE, i));
		}
		addDirect(gregtech6.block.multiblock.GTLightningRodBlock.Item.KEY_ENERGY);
		addDirect(gregtech6.block.multiblock.GTLightningRodBlock.Item.KEY_CAPACITY);
		// attachments: the two family templates + the attachment material words
		addDirect(gregtech6.registry.GT6Attachments.TAP_DISPLAY_KEY);
		addDirect(gregtech6.registry.GT6Attachments.FUNNEL_DISPLAY_KEY);
		for (gregtech6.registry.GT6Attachments.AttachmentRow tRow : gregtech6.registry.GT6Attachments.ROWS) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Attachments.matUnitKeyOf(tRow));
		}
		// the two wood gearboxes (the atomic attachment extras, the Loader :1668/:1669 rows)
		addDirect("block.gt6.gearbox");
		addDirect("block.gt6.transformer_rotation");
	}

	/** Dedup across the row-family walks (the en addRowMatUnit mirror). */
	private void addRowUnit(java.util.Set<String> aEmitted, String aKey) {
		if (aEmitted.add(aKey)) addDirect(aKey);
	}

	/**
	 * The B1 wire-domain composed-display units (task p20-i18n-compose-wires): the five
	 * position-param templates the {@code GTWireBlock.displayNameOf} compose fills
	 * ({@code gt6.wire.display[.plain]} + the {@code gt6.wire.form.*} units), the two cover
	 * tier-ladder templates (the tier slot rides a plain literal — the CS.java:154 voltage
	 * numerals are proper nouns in BOTH locales, no small-unit keys) and the laser atomic
	 * exemption ({@code block.gt6.wire_laser}, the material-less family stays a whole-string
	 * key on both faces). All hand rows in the reference table — the zh wording evidence
	 * lives in the gen script's hand-layer comments. Emitted here so the en-side template
	 * walks (GT6EnUs.addElectricWires/addCovers) have their exact zh mirror: the composed
	 * zh wire names (e.g. "{@code 12×锡线缆}", "{@code 红色合金导线}") then cost ZERO new
	 * material translations on top of these eight units.
	 */
	private void addWireDomainUnits() {
		addDirect("gt6.wire.display");
		addDirect("gt6.wire.display.plain");
		addDirect("gt6.wire.form.wire");
		addDirect("gt6.wire.form.cable");
		addDirect("gt6.wire.form.wirelamp");
		addDirect("gt6.cover.conveyor.display");
		addDirect("gt6.cover.robot_arm.display");
		addDirect("block.gt6.wire_laser");
	}

	/** The item + block prefix tab titles and the special MTE-category tabs (mirror of GT6EnUs.addTabTitles/addBlockTabTitles + the tab literals). */
	private void addTabTitles() {
		for (OreDictPrefix tPrefix : GTMaterialItems.tabPrefixes()) {
			addFromFamily("itemgroup", tPrefix.mNameInternal,
				"itemGroup.gt6." + MaterialPrefixItem.snakeCase(tPrefix.mNameInternal));
		}
		for (OreDictPrefix tPrefix : GTMaterialBlocks.tabPrefixes()) {
			addFromFamily("itemgroup", tPrefix.mNameInternal,
				"itemGroup.gt6." + MaterialPrefixItem.snakeCase(tPrefix.mNameInternal));
		}
		// the special tabs have no dump face (the 1.7.10 dump's itemGroup family holds prefix
		// tabs only) — their titles ride the hand rows, keyed by the same literals/constants
		// the en walk uses so the faces cannot drift
		addDirect("itemGroup.gt6.chests");
		addDirect("itemGroup.gt6.machines");
		addDirect("itemGroup.gt6.multiblocks");
		addDirect("itemGroup.gt6.fluid_containers");
		addDirect("itemGroup.gt6.fluid_pipes");
		addDirect("itemGroup.gt6.electric_wires");
		addDirect(GTWires.REDSTONE_TAB_TITLE_KEY);
		addDirect(GTWires.LASER_TAB_TITLE_KEY);
		addDirect(GT6Tools.TAB_TITLE_KEY);
	}

	/** Only the hand-translated in-use prefix templates (mirror of GT6EnUs.addPrefixTemplates over OP.VALUES). */
	private void addPrefixTemplates() {
		Set<String> tSeen = new HashSet<>();
		for (OreDictPrefix tPrefix : OreDictPrefix.VALUES) {
			String tKey = "gt6.tagprefix." + MaterialPrefixItem.snakeCase(tPrefix.mNameInternal);
			if (!tSeen.add(tKey)) continue; // same snake_case-collision guard as the en walk
			addDirect(tKey);
		}
	}

	/**
	 * The material small units: the shared {@link GT6EnUs#materialWalkEmittedKeys} seam (alias
	 * merge, first mID wins) joined against the dump family — the seam's Map form carries the
	 * merged material identity the mNameInternal family lookup needs (task
	 * p21-i18n-walk-seam-normalize; no zh-side walk copy remains).
	 */
	private void addMaterialNames() {
		GT6EnUs.materialWalkEmittedKeys().forEach((tKey, tMaterial) ->
			addFromFamily("material", tMaterial.mNameInternal, tKey));
	}

	/**
	 * The atomic misc units — every key here mirrors a GT6EnUs literal/constant and is part of
	 * NO composed domain (the B-wave cards shrink those; see the class javadoc). The cover
	 * names are the eight atomic covers; the conveyor/robot-arm tier ladders compose from the
	 * {@link #addWireDomainUnits()} templates since p20-i18n-compose-wires.
	 */
	private void addMiscUnits() {
		addDirect("item.gt6.crowbar");
		addDirect("item.gt6.cutter");
		addDirect("item.gt6.chisel");
		addDirect("item.gt6.file"); // task p24-tool-system — the zh face rides the hand rows
		addDirect("item.gt6.saw");
		addDirect("item.gt6.builder_wand"); // task p24-builder-wand — the dump tool.name face is untranslated ASCII, the hand row composes from 建筑之杖 (itemGroup.toolHeadBuilderwand :18079 / oredict suffix :91577)
		addDirect("item.gt6.screwdriver"); // task p24-screwdriver-item — same hand-row face
		addDirect("item.gt6.hammer"); // task p25-tool-hammer-wrench — the hand row composes from 锤 (toolHeadHammer dump face 锤头 :3290, head-word first)
		addDirect("item.gt6.wrench"); // task p25-tool-hammer-wrench — the hand row composes from 扳手 (toolHeadWrench dump face 扳手头 :3319)
		addDirect("item.gt6.cover_redstone_emitter");
		addDirect("item.gt6.cover_redstone_conductor_in");
		addDirect("item.gt6.cover_redstone_conductor_out");
		addDirect("item.gt6.cover_redstone_machine_switch");
		addDirect("item.gt6.cover_shutter");
		addDirect("item.gt6.cover_item_filter");
		addDirect("item.gt6.cover_auto_redstone_machine_switch");
		addDirect("item.gt6.cover_controller");
		addDirect("item.gt6.integrated_circuit");
		addDirect(GT6Circuits.TOOLTIP_KEY);
		addDirect(GT6JeiPlugin.INFO_KEY_COKE_OVEN);
		addDirect("block.gt6.example_chest");
		addDirect("fluid.gt6.iron_molten");
		addDirect("fluid.gt6.natural_gas");
	}

	/** Family join: derive nothing here beyond the caller's key — look the dump suffix up, skip absent/review rows. */
	private void addFromFamily(String aKind, String aSource, String aKey) {
		RefRow tRow = reference.get(aKind) == null ? null : reference.get(aKind).get(aSource);
		if (tRow != null && !tRow.skipped()) add(aKey, tRow.value());
	}

	/** Hand-row join: the key IS the final gt6 lang key (status=hand direct rows); skip absent/review rows. */
	private void addDirect(String aKey) {
		RefRow tRow = reference.get("direct") == null ? null : reference.get("direct").get(aKey);
		if (tRow != null && !tRow.skipped()) add(aKey, tRow.value());
	}

	/**
	 * Parses {@link #REFERENCE_RESOURCE}: {@code #}-comment and blank lines skipped, data rows
	 * are {@code kind<TAB>source<TAB>value<TAB>status}. Package-private static so the parity
	 * test reuses the single parse implementation (it asserts no hand row is orphaned).
	 */
	static Map<String, Map<String, RefRow>> loadReference() {
		Map<String, Map<String, RefRow>> rTable = new HashMap<>();
		InputStream tStream = GT6ZhCn.class.getResourceAsStream(REFERENCE_RESOURCE);
		if (tStream == null) throw new IllegalStateException("reference table missing on the classpath: " + REFERENCE_RESOURCE);
		try (BufferedReader tReader = new BufferedReader(new InputStreamReader(tStream, StandardCharsets.UTF_8))) {
			String tLine;
			while ((tLine = tReader.readLine()) != null) {
				if (tLine.isEmpty() || tLine.charAt(0) == '#') continue;
				String[] tFields = tLine.split("\t", -1);
				if (tFields.length != 4) throw new IllegalStateException("malformed reference row: " + tLine);
				rTable.computeIfAbsent(tFields[0], k -> new HashMap<>()).put(tFields[1], new RefRow(tFields[2], tFields[3]));
			}
		} catch (IOException aE) {
			throw new IllegalStateException("failed to read " + REFERENCE_RESOURCE, aE);
		}
		return rTable;
	}
}
