package gregtech6.datagen;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import gregapi.oredict.OreDictPrefix;
import gregtech6.fluid.GTFluids;
import gregtech6.item.GT6Circuits;
import gregtech6.item.MaterialPrefixItem;
import gregtech6.jade.GT6FluidProvider;
import gregtech6.jade.GT6MachineProvider;
import gregtech6.jei.GT6JeiPlugin;
import gregtech6.registry.GT6Tools;
import gregtech6.registry.GT6OreBlocks;
import gregtech6.registry.GTMaterialBlocks;
import gregtech6.registry.GTMaterialItems;
import gregtech6.registry.GTWires;
import net.minecraft.data.PackOutput;
import net.minecraftforge.common.data.LanguageProvider;

/**
 * zh_cn lang, the A-wave small-unit companion of {@link GT6EnUs} (task p20-i18n-zhcn-provider,
 * ADR 2026-09-06-p20-i18n-zhcn-pipeline): zh_cn.json is GENERATED by this provider — the
 * hand-written-JSON red line forbids editing it directly. The translation VALUES come from the
 * committed reference table {@code /gregtech6/lang/zh_cn_ref.tsv} (produced by
 * {@code mdk/tools/gen_zhcn_ref.py} from the GT6 1.7.10 zh lang dump + a hand-translation
 * layer); the lang KEYS are derived here with the same single
 * {@link MaterialPrefixItem#snakeCase} implementation the en provider uses, so no second
 * snake_case algorithm exists (the Python side of the pipeline deliberately carries zero key
 * logic, ADR §1.1).
 *
 * <p>Four small-unit walks over the same registry sources as {@link GT6EnUs} — three mirror the
 * en walk, the material walk consumes GT6EnUs's shared seam directly (per-key English fallback
 * for skipped rows is vanilla's built-in bilingual chain — LanguageManager.java:50-52 +
 * ClientLanguage.java:29-46 — so zero fallback code lives here):
 * <ol>
 * <li>{@link #addTabTitles()} — the creative tab titles: item prefix tabs
 *     ({@code itemGroup.gt6.<snake>} over {@link GTMaterialItems#tabPrefixes()}), block prefix
 *     tabs (over {@link GTMaterialBlocks#tabPrefixes()}) and the special MTE-category tabs,
 *     joined against the dump's {@code itemGroup.<camel>} family or the hand rows;</li>
 * <li>{@link #addPrefixTemplates()} — the {@code gt6.tagprefix.<snake>} display templates.
 *     The en provider emits all 467 OP prefixes; zh emits ONLY the hand-translated in-use set
 *     (status=hand direct rows, ADR §1.2 — the dump has no authoritative template face, and
 *     affix stripping would be statistical generalisation multiplied by 1273 materials). The
 *     parity test (GT6LangParityTest) structurally guarantees zh ⊆ en;</li>
 * <li>{@link #addMaterialNames()} — the {@code gt6.material.<snake>} small units, the shared
 *     {@link GT6EnUs#materialWalkEmittedKeys} seam (alias merge, first mID wins) joined against
 *     the dump's {@code gt.material.<Pascal>} family (the Map form carries the merged material
 *     identity the TSV family join needs — task p21-i18n-walk-seam-normalize);</li>
 * <li>{@link #addMiscUnits()} — the atomic misc keys (tools, the eight atomic covers, the
 *     circuit selector tag + its configuration tooltip, the JEI coke-oven info page, the
 *     example chest, the two port fluids). The COMPOSED domains became B-wave template keys
 *     (p20-i18n-compose-wires/-rows); B1's face is {@link #addWireDomainUnits()} and B2's faces are
     *     {@link #addStoneVariantUnits()} + {@link #addRowDomainUnits()} — with the
     *     B-wave landed, the parity test's composed-domain negative assertions are
     *     EMPTY (the closeout state).
 * </ol>
 *
 * <p>Rows with status {@code review} (pure-ASCII dump values, suspected untranslated, e.g.
 * {@code gt.material.Magnite=Magnite}, tmp/gregtech.lang:5003) and rows with no reference
 * entry at all are skipped: the runtime falls back to English per key. The {@code mte} family
 * in the TSV is deliberately unused here — it is inert census data until the MTE ID-join
 * subface lands (arch card tasks.p20-arch-i18n).
 *
 * <p>Non-final on purpose: GT6LangParityTest records {@code add()} through a same-package
 * subclass (the GT6EnUsJeiInfoTest:52-64 posture) to collect both providers' key sets in a
 * bare JVM without a datagen run.
 */
public class GT6ZhCn extends LanguageProvider {

	/** Classpath location of the generated reference table (rides the jar, ADR §1.1). */
	static final String REFERENCE_RESOURCE = "/gregtech6/lang/zh_cn_ref.tsv";

	/** One reference row: the translation value and its pipeline status. */
	record RefRow(String value, String status) {
		/** review rows are suspected-untranslated dump entries — the provider skips them. */
		boolean skipped() {
			return "review".equals(status);
		}
	}

	private final Map<String, Map<String, RefRow>> reference;

	public GT6ZhCn(PackOutput output) {
		super(output, GT6DataGenerators.MOD_ID, "zh_cn");
		this.reference = loadReference();
	}

	@Override
	protected void addTranslations() {
		addTabTitles();
		addPrefixTemplates();
		addMaterialNames();
		addMiscUnits();
		addBatteryFamily(); // task p29-w4-battery-storage — the 37+5+7+12 storage face (hand rows, the tsv direct band)
		addBackfillUnits();     // task p23-i18n-zh-442-backfill
		addWireDomainUnits();
		addStoneVariantUnits();
		addStaticStorageUnits(); // task p20-i18n-compose-rows
		addRowDomainUnits();    // task p20-i18n-compose-rows
		addMoldCrucibleUnits(); // task p27-lang-fix-batch2 — the ledger §6 zh gap
		addGrassUnits();        // task p24-grass-block
		addFoamSprayUnits();    // task p25-c-foam-pipe-spray
		addKitchenUnits();      // task p26-kitchen-pot-bowl
		addCrucibleJadeUnits(); // task p28-crucible-jade-face
		addMachineJadeUnits();  // task p34-hygiene-lang — the machine/fluid jade band (hand rows, the tsv direct band)
		addAnvilUnits();        // task p28-c-anvil
		addPocketUnits();       // task p29-w5-t7-pocket-eight — the 8+7 pocket face (hand rows, no dump face exists)
		addArmorUnits();        // task p29-w5-t8-armor-24
		addTreeUnits();         // task p30-w6-t1-trees-nine — the 27 tree-family rows (hand, the tsv direct band)
		addSurfaceUnits();      // task p30-w6-rocks-sticks
		addSurfacePlantUnits(); // task p30-w6-t2-surface-blocks — the 8 plant/log rows (hand, the tsv direct band)
		// task p30-ore-1-mech — 模板钉说明，本卡零键（zh ratchet 0）：矿域注册面
		//（GT6OreBlocks，26 族 x 74 form-rows x M=53）不加任何 zh 键——每个矿块物品
		// 走既有 gt6.tagprefix.<prefix_snake> 模板组合（addPrefixTemplates 覆盖全 OP 前缀，
		// normal/broken 同族前缀、small 走 OP.oreSmall）。剩余面归波次卡③（datagen）：
		// 26x3 逐族模板键（可选）+ 唯一创造栏页签标题 itemGroup.gt6.ore_vanillastone
		//（GT6OreBlocks.TAB_TITLE_KEY，"石矿"）。
		addOreTabTitle(); // task p30-ore-3-datagen — ore-1 注记的卡③面（唯一新键，dump itemgroup 家族行 矿石）
		addBeeUnits();          // task p31-bees-lv1 — the 20 comb names + the Bees tab + the 11 honey/bee-row fluids (hand rows, the tsv direct band; the dump carries no comb faces)
		addBumbleUnits();       // task p33-bees-lv3-a-items — the 80 species names + the 8 face formats (the dump gt.multiitem.bumblebee.* faces verbatim, the tsv direct band)
		addUsbStickUnits();     // task p32-usb-data — the 4 stick names + the 4 tooltips (hand rows, the tsv direct band; the dump USB face)
		addPlaceablesUnits();   // task p32-placeables — the 8 deco/placed-pile names (the lantern + the sandwich + the six placed piles; hand rows, the tsv direct band)
		addLaserGasUnits();     // task p32-qu-laser-domain — the 2 gas emitter names + the 2 tooltips (hand rows, the dump :10379/:10395 faces)
	}

	/**
	 * The USB Stick zh faces (task p32-usb-data, the addArmorUnits shape): the 4 display
	 * names + the 4 per-tier tooltip keys, riding the reference table's hand layer — the
	 * values are the DUMP faces verbatim (tmp/gregtech.lang:10745-10752: "USB 1.0".."USB
	 * 4.0", tooltip 储存数据). The data-state tooltip lines stay RUNTIME literals (the
	 * upstream Behavior_DataStorage hardcoded-en face; the dump carries zero rows for
	 * them — the GT6EnUs.addUsbSticks note).
	 */
	private void addUsbStickUnits() {
		for (byte tTier = 1; tTier <= 4; tTier++) {
			addDirect("item.gt6.usb_stick_" + tTier);
			addDirect("item.gt6.usb_stick_" + tTier + ".tooltip");
		}
	}

	/**
	 * The gas laser emitter zh faces (task p32-qu-laser-domain, the addUsbStickUnits
	 * shape): the 2 display names + the 2 tooltip keys, riding the reference table's hand
	 * layer — the values are the DUMP faces verbatim (tmp/gregtech.lang :10379/:10395:
	 * 空的气体-激光镭射器 / 二氧化碳激光镭射器, the tooltips are the :384/:394 description
	 * columns' hand rows, no dump faces).
	 */
	private void addLaserGasUnits() {
		addDirect("item.gt6.comp_laser_gas_empty");
		addDirect("item.gt6.comp_laser_gas_empty.tooltip");
		addDirect("item.gt6.comp_laser_gas_co2");
		addDirect("item.gt6.comp_laser_gas_co2.tooltip");
	}

	/**
	 * The Hazmat armor zh faces (task p29-w5-t8-armor-24, the addAnvilUnits shape): the
	 * 24 display names + the 24 per-piece tooltip keys, all riding the reference table's
	 * hand layer — the values are the DUMP faces verbatim (tmp/gregtech.lang:927-974,
	 * the gt.armor.hazmat.* + *.tooltip_main families keyed onto the modern snake ids).
	 * Hand rows (the reference dump keys are the 1.7 unlocalized forms, lifted onto the
	 * direct hand layer — the TSV regen and this walk land in the SAME commit).
	 */
	private void addArmorUnits() {
		for (gregtech6.items.armor.GT6ArmorMaterials.SuitRow tSuit : gregtech6.items.armor.GT6ArmorMaterials.SUITS) {
			for (int i = 0; i < gregtech6.items.armor.GT6ArmorMaterials.PIECE_WORDS.length; i++) {
				addDirect("item.gt6." + tSuit.pieceId(i));
				addDirect("item.gt6." + tSuit.pieceId(i) + ".tooltip");
			}
		}
	}

	/**
	 * The surface deco family zh faces (task p30-w6-rocks-sticks): the rock template
	 * (hand composition "%s地表岩" over the dump's generic MTE name 石头 :13578 — the
	 * per-material composed form, the addStoneVariantUnits canon) and the stick (the
	 * dump :13577 木棍 verbatim). Hand rows — the reference dump keys are the meta-keyed
	 * 1.7 forms, lifted onto the direct hand layer (the addAnvilUnits posture; the
	 * TSV rows and this walk land in the SAME commit, the noHandRowIsOrphaned pin).
	 */
	private void addSurfaceUnits() {
		addDirect("gt6.surface.rock");
		addDirect("block.gt6.surface_stick");
	}

	/**
	 * The surface-plants + fallen-woods zh faces (task p30-w6-t2-surface-blocks, the
	 * GT6EnUs.addSurfacePlants mirror): 8 display names, all hand rows — no upstream zh
	 * dump face exists for these blocks (the t1 tree-family precedent). The standard
	 * Chinese words: 荧光莲 (the Glowtus lily), 浆果丛 (the bush MTE's 丛 word), 黑沙
	 * (the magnetite sand), 草皮 (Turf), and the four special-wood logs 枯/腐朽/苔藓/冰冻
	 * 原木 (the MT.WOODS Dead/Rotten/Mossy/Frozen wood words).
	 */
	private void addSurfacePlantUnits() {
		addDirect("block.gt6.glowtus");
		addDirect("block.gt6.berry_bush");
		addDirect("block.gt6.black_sand");
		addDirect("block.gt6.turf");
		addDirect("block.gt6.dead_log");
		addDirect("block.gt6.rotten_log");
		addDirect("block.gt6.mossy_log");
		addDirect("block.gt6.frozen_log");
	}

	/**
	 * The anvil family zh faces (task p28-c-anvil) — the upstream zh dump rows VERBATIM
	 * (tmp/gregtech.lang: "石头砧" = meta 32025 Stone Anvil, "黑石砧" = meta 32095
	 * Blackstone Anvil). Hand rows (the reference dump keys are the meta-keyed 1.7 forms,
	 * lifted onto the direct hand layer — the addDirect absent-row skip is why the TSV
	 * regen and this walk land in the SAME commit, the noHandRowIsOrphaned pin).
	 */
	private void addAnvilUnits() {
		addDirect("block.gt6.stone_anvil");
		addDirect("block.gt6.blackstone_anvil");
	}

	/**
	 * The pocket multitool family zh faces (task p29-w5-t7-pocket-eight, 15 hand rows):
	 * NO dump face exists (the upstream 1.7.10 lang carries zero pocket rows — the
	 * tmp/gregtech.lang sweep found only the written-book mention), so all fifteen ride
	 * the HAND layer directly (the addAnvilUnits shape; these keys are registry-path
	 * keyed, not meta-keyed, so plain add rows). Display names translate the :176-183
	 * registration rows ("便攜多功能工具" style + the （X） parenthetical tails); the
	 * tooltips translate the note columns + the switch hint. Provenance: hand, slug
	 * p29-w5-t7-pocket-eight, 15 rows = the en band parity. Table-tail append, append-only.
	 */
	private void addPocketUnits() {
		add("item.gt6.pocket_multitool", "便携多功能工具");
		add("item.gt6.pocket_multitool_knife", "便携多功能工具（刀）");
		add("item.gt6.pocket_multitool_saw", "便携多功能工具（锯）");
		add("item.gt6.pocket_multitool_file", "便携多功能工具（锉）");
		add("item.gt6.pocket_multitool_screwdriver", "便携多功能工具（螺丝刀）");
		add("item.gt6.pocket_multitool_wire_cutter", "便携多功能工具（剪线钳）");
		add("item.gt6.pocket_multitool_scissors", "便携多功能工具（剪刀）");
		add("item.gt6.pocket_multitool_chisel", "便携多功能工具（凿子）");
		add(gregtech6.items.tools.pocket.GTPocketMultitoolItem.SWITCH_TOOLTIP_KEY, "潜行右键切换模式");
		add("tooltip.gt6.pocket.multitool", "7 种工具合而为一！");
		add("tooltip.gt6.pocket.saw", "采木板更快，采原木较慢，可以采集冰。");
		add("tooltip.gt6.pocket.file", "采集铁栏杆与其类似方块更快");
		add("tooltip.gt6.pocket.wire_cutter", "采集线缆和导线更快");
		add("tooltip.gt6.pocket.scissors", "拿着它的时候别到处乱跑！");
		add("tooltip.gt6.pocket.chisel", "服务器延迟高时请务必小心使用！");
	}

	/**
	 * The kitchen family zh faces (task p26-kitchen-pot-bowl) — the upstream zh dump rows
	 * VERBATIM (tmp/gregtech.lang: "木质浸洗盆" :13542 = meta 32721 Wooden Bathing Pot,
	 * "浸洗盆" :13529 = meta 32708 Bathing Pot, "搅拌盆" :13527 = meta 32706 Ceramic Bowl,
	 * "粘土碗" :10110 = meta 995 Clay Bowl). Hand rows (the reference dump keys are the
	 * meta-keyed 1.7 forms, not these registry-path keys). Task p27-lang-fix — the TAB
	 * RETIREMENT: the former hand tab title ("itemGroup.gt6.kitchen" = "GT6 厨具") is
	 * gone with the tab itself (the user ruling: the pot/bowl rows are processing
	 * machines, not cookware — they ride the machines tab now); the four display names
	 * KEEP their dump-verbatim faces (ledger §1.2).
	 */
	private void addKitchenUnits() {
		add("block.gt6.bathing_pot_wood", "木质浸洗盆");
		add("block.gt6.bathing_pot_steel", "浸洗盆");
		add("block.gt6.mixing_bowl", "搅拌盆");
		add("block.gt6.juicer", "榨汁机"); // task p33-food-machines-kitchen — the dump gt.multitileentity.32722 face 榨汁机 verbatim (tmp/gregtech.lang:13543)
		add("item.gt6.clay_bowl", "粘土碗");
	}

	/**
	 * The crucible Jade face zh units (task p28-crucible-jade-face, 4 hand rows — the final
	 * key set after the TFRU 33c22beb ruling): no dump face exists (upstream 1.7.10 has zero
	 * WAILA integration), so these ride the reference table's hand layer via
	 * {@link #addDirect} — the addDirect absent-row skip is why the TSV regen and this walk
	 * land in the SAME commit (the noHandRowIsOrphaned pin otherwise surfaces the gap).
	 * The total line's 内容物 label IS the TFRU LH.CONTENT prefix form; the K unit stays
	 * bare (the thermometer anchor MultiTileEntitySmeltery.java:512 carries it untranslated).
	 */
	private void addCrucibleJadeUnits() {
		addDirect("gt6.jade.crucible.temperature");
		addDirect("gt6.jade.crucible.total");
		addDirect("gt6.jade.crucible.empty");
		addDirect("gt6.jade.crucible.more");
	}

	/**
	 * The machine/fluid Jade face zh units (task p34-hygiene-lang, 9 hand rows — the
	 * addCrucibleJadeUnits shape): the keyed machine tooltip band (progress in its two
	 * unit faces / energy / input band / the two multiblock states / error) + the two
	 * fluid tank-group titles. No dump face exists (upstream has zero WAILA integration),
	 * so these ride the reference table's hand layer via {@link #addDirect} — the py rows,
	 * this walk and the TSV regen land in the SAME commit (the noHandRowIsOrphaned pin
	 * otherwise surfaces the gap).
	 */
	private void addMachineJadeUnits() {
		addDirect(GT6MachineProvider.LANG_PROGRESS_SECONDS);
		addDirect(GT6MachineProvider.LANG_PROGRESS_TICKS);
		addDirect(GT6MachineProvider.LANG_ENERGY);
		addDirect(GT6MachineProvider.LANG_INPUT);
		addDirect(GT6MachineProvider.LANG_STRUCTURE_FORMED);
		addDirect(GT6MachineProvider.LANG_STRUCTURE_INCOMPLETE);
		addDirect(GT6MachineProvider.LANG_ERROR);
		addDirect(GT6FluidProvider.LANG_GROUP_IN);
		addDirect(GT6FluidProvider.LANG_GROUP_OUT);
	}

	/**
	 * The C-Foam spray family zh faces (task p25-c-foam-pipe-spray, the addGrassUnits
	 * shape): the 32 item display names (16 C-Foam + 16 Advanced owned) + the family tab +
	 * the 2 tooltip lines. All 35 ride the reference table's hand layer — the 32 item names
	 * are the DUMP faces verbatim (metas 1100+2i/1132+2i, tmp/gregtech.lang:9350-9431),
	 * the tooltip template splits the dump's gt.behaviour.foamspray.N tooltip at the colour
	 * word (the %s slot rides the untranslated DYE_NAMES arg, the p22 spraycan.paint form)
	 * and the owned warning is hand (upstream :259 en only).
	 */
	private void addFoamSprayUnits() {
		for (String tDye : gregtech6.item.spraycan.GTSprayCanItem.DYE_IDS) {
			addDirect("item.gt6.foam_spray_" + tDye);
			addDirect("item.gt6.foam_spray_owned_" + tDye);
		}
		addDirect(gregtech6.registry.GT6FoamSprays.TAB_TITLE_KEY);
		addDirect(gregtech6.item.foamspray.GT6FoamSprayItem.FOAM_TOOLTIP_KEY);
		addDirect(gregtech6.item.foamspray.GT6FoamSprayItem.OWNED_TOOLTIP_KEY);
	}

	/**
	 * The grass family zh faces (task p24-grass-block, the GT6EnUs.addGrassBlocks mirror):
	 * the 6 variant display names (all "草方块" — the en "Grass" parity ruling, no colour
	 * prefix) + the 2 tooltip lines. All 8 ride the reference table's hand layer (direct
	 * rows; the tooltip zh face is the dump's {@code gt.grass.tooltip} wording,
	 * tmp/gregtech.lang:3228, plus a hand translation for the :3229 row the dump never
	 * translated).
	 */
	private void addGrassUnits() {
		for (String tPath : gregtech6.registry.GTGrassBlocks.PATHS) {
			addDirect("block.gt6." + tPath);
		}
		addDirect(gregtech6.block.GTGrassBlock.TOOLTIP_KEY);
		addDirect(gregtech6.block.GTGrassBlock.TOOLTIP_SPRAY_KEY);
	}

	/**
	 * The tree family zh faces (task p30-w6-t1-trees-nine, the GT6EnUs.addTreeBlocks
	 * mirror): the 27 block display names, all hand rows (no upstream zh dump face exists
	 * for the 1.7.10 tree blocks — the anvil-family precedent), walked from
	 * {@link gregtech6.registry.GT6TreeBlocks#KINDS}: "&lt;zhName&gt;树苗/原木/树叶" over the
	 * TSV's direct band.
	 */
	private void addTreeUnits() {
		for (gregtech6.block.tree.GT6TreeKind tKind : gregtech6.registry.GT6TreeBlocks.KINDS) {
			addDirect("block.gt6." + gregtech6.registry.GT6TreeBlocks.path(tKind, "_sapling"));
			addDirect("block.gt6." + gregtech6.registry.GT6TreeBlocks.path(tKind, "_log"));
			addDirect("block.gt6." + gregtech6.registry.GT6TreeBlocks.path(tKind, "_leaves"));
		}
	}

	/**
	 * The bee family zh faces (task p31-bees-lv1, the addTreeUnits shape): the Bees tab
	 * title, the 20 comb display names and the 11 honey-family + bee-row fluid display
	 * names, all riding the reference table's hand layer (the dump carries no comb faces —
	 * the 蜜脾 wording is hand zh over the 黄蜂蜂巢 hive face zh_cn_ref.tsv:6569; the fluid
	 * words reuse the dump material faces where they exist: 蜂蜜/蜜露/胶乳).
	 * Hand rows (the TSV regen and this walk land in the SAME commit).
	 */
	private void addBeeUnits() {
		addDirect("itemGroup.gt6.bee");
		addDirect("block.gt6.bumble_hive"); // task p32-bees-lv2 — the MTE 32755 hive block (hand row, the tsv direct band)
		addDirect("block.gt6.bumbliary");          // task p33-bees-lv3-b-bumbliary — the MTE 32741 face (the dump gt.multitileentity.32741 row, tsv auto band)
		addDirect("block.gt6.bumbliary_advanced"); // the MTE 32007 face (the dump gt.multitileentity.32007 row, tsv auto band)
		for (gregtech6.registry.GT6BeeCombs.CombSpec tSpec : gregtech6.registry.GT6BeeCombs.COMB_SPECS) {
			addDirect("item.gt6." + tSpec.itemId());
		}
		for (GTFluids.ChemicalFluidSpec tSpec : GTFluids.HONEY_FLUID_SPECS) {
			addDirect(tSpec.descriptionId());
		}
		for (GTFluids.ChemicalFluidSpec tSpec : GTFluids.BEE_ROW_FLUID_SPECS) {
			addDirect(tSpec.descriptionId());
		}
	}

	/**
	 * The bumblebee family zh faces (task p33-bees-lv3-a-items, the addBeeUnits shape):
	 * the 80 species names and the 8 name-format rows — the dump's
	 * {@code gt.multiitem.bumblebee.*} faces verbatim (雄性/雌性 prefix, 蜂后/(死亡)
	 * suffix, (已扫描) tail), the tsv direct band (hand rows land in the SAME commit).
	 */
	private void addBumbleUnits() {
		for (gregtech6.items.bees.GT6Bumbles.SpeciesRow tRow : gregtech6.items.bees.GT6Bumbles.SPECIES) {
			addDirect(tRow.langKey());
		}
		for (gregtech6.items.bees.GT6Bumbles.FaceRow tFace : gregtech6.items.bees.GT6Bumbles.FACES) {
			addDirect(tFace.formatKey());
		}
	}

	/**
	 * The 442-key zh backfill (task p23-i18n-zh-442-backfill), non-tagprefix face: the 76
	 * atomic keys whose en counterpart is a whole-string {@code add} in {@link GT6EnUs} —
	 * the barrel/fluid-pipe/machine blocks, the fluid display names, the P22 spray-can
	 * items + tooltips, the five backfill materials (the dump rows are review/absent, so
	 * they cannot ride the {@link #addMaterialNames()} family join) and the two new tabs.
	 * (The 365 {@code gt6.tagprefix.*} keys need NO new walk here —
	 * {@link #addPrefixTemplates()} already walks every {@link OreDictPrefix#VALUES} key and
	 * only the reference-table hand rows were missing.) Every key mirrors an en literal and
	 * carries a hand row in the reference table; the wording evidence lives in the gen
	 * script's backfill tables.
	 */
	private void addBackfillUnits() {
		// blocks: barrels (Drum = 鼓), the wood barrel (dump MTE 6990 join), the machines,
		// the coke-oven multiblock pair, the two atomic legacy electric wires, the pipes
		addDirect("block.gt6.advanced_crafting_table"); // task p24-act-machine
		addDirect("block.gt6.barrel_adamantium");
		addDirect("block.gt6.barrel_awakened_draconium");
		addDirect("block.gt6.barrel_draconium");
		addDirect("block.gt6.barrel_gaia_spirit");
		addDirect("block.gt6.barrel_infinity");
		addDirect("block.gt6.barrel_logistics");
		addDirect("block.gt6.barrel_metal");
		addDirect("block.gt6.barrel_netherite");
		addDirect("block.gt6.barrel_plastic");
		addDirect("block.gt6.barrel_tantalum_hafnium_carbide");
		addDirect("block.gt6.barrel_titanium");
		addDirect("block.gt6.barrel_tungsten");
		addDirect("block.gt6.barrel_tungsten_alloy");
		addDirect("block.gt6.barrel_tungstensteel");
		addDirect("block.gt6.barrel_void_metal");
		addDirect("block.gt6.barrel_wood");
		// task p32-qu-laser-domain — the CO2 Laser family (the dump :10845-10849 faces verbatim)
		addDirect("block.gt6.co2_laser");
		addDirect("block.gt6.co2_laser_t2");
		addDirect("block.gt6.co2_laser_t3");
		addDirect("block.gt6.co2_laser_t4");
		addDirect("block.gt6.co2_laser_t5");
		// task p26-crucible-multiblock — the LARGE crucible family (the dump :11294/:11364
		// rows: 17309=大型钢坩埚, 18009=钢壁板)
		addDirect("block.gt6.crucible_steel");
		addDirect("block.gt6.crucible_steel_wall");
		// task p29-w3-distill-crucible — the crucible ladder + the twin towers (the dump
		// :11288-11296/:15186/:11246 faces; the ladder walls compose over the EXISTING
		// gt6.row.mat words — no wall rows here, the zh template rides the same key)
		addDirect("block.gt6.crucible_stainless_steel");
		addDirect("block.gt6.crucible_invar");
		addDirect("block.gt6.crucible_titanium");
		addDirect("block.gt6.crucible_tungstensteel");
		addDirect("block.gt6.crucible_tungsten");
		addDirect("block.gt6.crucible_tantalum_hafnium_carbide");
		addDirect("block.gt6.crucible_adamantium");
		addDirect("block.gt6.distillation_tower");
		addDirect("block.gt6.cryo_distillation_tower");
		addDirect("block.gt6.crank");
		addDirect("block.gt6.crusher");
		// task p28-c-ulv-dynamo-row — the dynamo family name face (the W1 classes' deferred
		// lang, the ParityTest registry-coverage gate): the electric rows are the dump faces
		// verbatim (gt.multitileentity.10111-10115 = 发电机 (LV..IV), tmp/gregtech.lang
		// :10850-10854), the T0 ULV row hand (VN[0]; upstream ships no ULV dynamo), the flux
		// rows the :10997-11001 faces verbatim
		addDirect("block.gt6.electric_dynamo");
		addDirect("block.gt6.electric_dynamo_t2");
		addDirect("block.gt6.electric_dynamo_t3");
		addDirect("block.gt6.electric_dynamo_t4");
		addDirect("block.gt6.electric_dynamo_t5");
		addDirect("block.gt6.electric_dynamo_ulv");
		addDirect("block.gt6.electrometer"); // task p26-sensors-core — the MTE 31015 dump row 电力传感器
		addDirect("block.gt6.electric_transformer"); // task p28-c-ulv-lv-transformer — hand row (no dump face in the port snapshot; the :881 registration wording + the standard zh machine word)
		// task p29-w4-eu-bridge — the three EU-bridge families (the dump faces verbatim,
		// gt.multitileentity.10001-10005 电力加热器 / 10011-10015 电动引擎 / 10021-10025
		// 电动机) + the Roasting template (gt.multitileentity.20171-20174 焙烧炉, the
		// Heat_T word slot)
		addDirect(gregtech6.registry.GTMachines.MACHINE_ROASTING_OVEN_UNIT_KEY);
		addDirect("block.gt6.electric_heater");
		addDirect("block.gt6.electric_heater_t2");
		addDirect("block.gt6.electric_heater_t3");
		addDirect("block.gt6.electric_heater_t4");
		addDirect("block.gt6.electric_heater_t5");
		addDirect("block.gt6.electric_engine");
		addDirect("block.gt6.electric_engine_t2");
		addDirect("block.gt6.electric_engine_t3");
		addDirect("block.gt6.electric_engine_t4");
		addDirect("block.gt6.electric_engine_t5");
		addDirect("block.gt6.electric_motor");
		addDirect("block.gt6.electric_motor_t2");
		addDirect("block.gt6.electric_motor_t3");
		addDirect("block.gt6.electric_motor_t4");
		addDirect("block.gt6.electric_motor_t5");
		addDirect("block.gt6.energy_source");
		addDirect("block.gt6.fe_battery"); // task p26-eu-bridge-outbound — tail-append
		addDirect("block.gt6.fe_converter"); // task p28-b-fe-converter-machine — tail-append
		addDirect("block.gt6.fe_source"); // task p28-b-fe-converter-machine — tail-append
		addDirect("block.gt6.fluidometer"); // task p26-sensors-core — the MTE 31006 dump row 流体体积传感器(单位: 升)
		addDirect("block.gt6.flux_dynamo"); // task p28-c-ulv-dynamo-row — the W1 family's deferred name face
		addDirect("block.gt6.flux_dynamo_t2");
		addDirect("block.gt6.flux_dynamo_t3");
		addDirect("block.gt6.flux_dynamo_t4");
		addDirect("block.gt6.flux_dynamo_t5");
		// task p32-qu-laser-domain — the laser domain (the dump faces verbatim,
		// gt.multitileentity.10101-10105 CO2激光器 / 10151-10155 激光接收器,
		// tmp/gregtech.lang :10845-10849/:10880-10884, the VN word slot)
		addDirect("block.gt6.laser_absorber");
		addDirect("block.gt6.laser_absorber_t2");
		addDirect("block.gt6.laser_absorber_t3");
		addDirect("block.gt6.laser_absorber_t4");
		addDirect("block.gt6.laser_absorber_t5");
		// task p32-qu-energizer — the dump gt.multitileentity.10121-10125 rows verbatim
		// (量子充能器 (T1..T5))
		addDirect("block.gt6.quantum_energizer");
		addDirect("block.gt6.quantum_energizer_t2");
		addDirect("block.gt6.quantum_energizer_t3");
		addDirect("block.gt6.quantum_energizer_t4");
		addDirect("block.gt6.quantum_energizer_t5");
		addDirect("block.gt6.lathe");
		addDirect("block.gt6.multiblock_coke_oven");
		addDirect("block.gt6.multiblock_coke_oven_bricks");
		addDirect("block.gt6.water_wheel"); // task p28-c-water-wheel — hand row (no dump face: upstream GT6 has no water wheel, the kTFRU rows are out-of-face by the ADR §1.1 filter)
		// (block.gt6.oven retired here — task p27-oven-heat-t-ladder moved the oven onto the
		// composed gt6.row.oven.display face, the addRowDomainUnits walk carries the template)
		addDirect("block.gt6.progressmeter"); // task p26-sensors-core — the MTE 31018 dump row 进度传感器
		// task p34-sensors-trivial-14 — the sensor batch (the zh MTE dump rows tmp/gregtech.lang
		// :13000-13017 verbatim where a dump face exists; 31023 has NO dump row — the dump
		// itself misses it, the census-erratum anchor — hand row following the 31001 form;
		// 31022's dump row ships the untranslated en literal, kept verbatim)
		addDirect("block.gt6.thermometer"); // the MTE 31000 dump row 温度传感器
		addDirect("block.gt6.luminometer"); // the MTE 31002 dump row 环境光度传感器
		addDirect("block.gt6.chronometer"); // the MTE 31003 dump row 精确时间传感器
		addDirect("block.gt6.gibblometer"); // the MTE 31001 dump row 锅炉压力传感器(单位: Gibbl)
		addDirect("block.gt6.kilogibblometer"); // the MTE 31023 hand row (no dump face) — the 31001 form at the Kilo divisor
		addDirect("block.gt6.itemometer"); // the MTE 31004 dump row 库存数量传感器
		addDirect("block.gt6.stackometer"); // the MTE 31005 dump row 库存堆栈传感器
		addDirect("block.gt6.bucketometer"); // the MTE 31007 dump row 流体体积传感器(单位: 桶)
		addDirect("block.gt6.kilobucketometer"); // the MTE 31022 dump row verbatim (the en literal)
		addDirect("block.gt6.lightweightometer"); // the MTE 31010 dump row 轻量级质量传感器
		addDirect("block.gt6.mediumweightometer"); // the MTE 31011 dump row 中量级质量传感器
		addDirect("block.gt6.heavyweightometer"); // the MTE 31012 dump row 重量级质量传感器
		addDirect("block.gt6.superheavyweightometer"); // the MTE 31013 dump row 超重量级质量传感器
		addDirect("block.gt6.tpsmeter"); // the MTE 31016 dump row TPS传感器
		addDirect("block.gt6.playercounter"); // the MTE 31017 dump row 玩家数量传感器
		addDirect("block.gt6.shredder");
		addDirect("block.gt6.wire_electric_1x");
		addDirect("block.gt6.wire_electric_2x");
		addDirect("block.gt6.wood_fluid_pipe_medium");
		addDirect("block.gt6.wood_fluid_pipe_small");
		// fluids: the 21 remaining display names (dump anchors 柴油/蒸馏水/幻露 per the research card)
		addDirect("fluid.gt6.cactuswater");
		addDirect("fluid.gt6.cold_water");
		addDirect("fluid.gt6.diesel");
		addDirect("fluid.gt6.distilled_water");
		addDirect("fluid.gt6.ethanol");
		addDirect("fluid.gt6.fuel");
		addDirect("fluid.gt6.hot_water");
		addDirect("fluid.gt6.jetfuel");
		addDirect("fluid.gt6.kerosine");
		addDirect("fluid.gt6.maplesap");
		addDirect("fluid.gt6.mnwtr");
		addDirect("fluid.gt6.nitrofuel");
		addDirect("fluid.gt6.petrol");
		addDirect("fluid.gt6.reedwater");
		addDirect("fluid.gt6.sap");
		addDirect("fluid.gt6.seawater");
		addDirect("fluid.gt6.spdew");
		addDirect("fluid.gt6.steam");
		addDirect("fluid.gt6.water_boiling");
		addDirect("fluid.gt6.water_geothermal");
		addDirect("fluid.gt6.waterdirty");
		// task p24-dye-chemical-fluids: the 16 dye-chemical display names + chlorine — the
		// dump carries all 17 faces (S:fluid.dye.chemical.* tmp/gregtech.lang:230-244,
		// S:fluid.chlorine=氯 :168); the keys ride the SAME GTFluids.dyeChemicalName
		// derivation the en walk and the FluidType descriptionIds use, so the two locale
		// faces cannot drift on the key side. Values are hand rows in the reference table.
		for (int i = 0; i < 16; i++) {
			addDirect("fluid.gt6." + GTFluids.dyeChemicalName(i));
		}
		addDirect("fluid.gt6.chlorine");
		// task p33-food-fluids-b1: the 220 food-fluid display names — the dump carries 153
		// faces (S:fluid.* rows: the milk/honey/juice/mash/tea/oil/sauce/cream/slime families
		// + the alcohol verbatim rows), the 67 binnie-external/derived ids are hand rows in
		// the reference table (果酒/威士忌/利口酒/白酒/白兰地 families); the keys ride the SAME
		// GTFluids.FOOD_B1_SPECS derivation the en walk and the FluidType descriptionIds use.
		for (GTFluids.AquaFluidSpec tSpec : GTFluids.FOOD_B1_SPECS) {
			addDirect("fluid.gt6." + tSpec.name());
		}
		// task p33-food-fluids-b2: the 103 drink-seam display names (94 potion brews + 9
		// residual FOOD-flag drink fluids) — the dump carries 102 faces (S:fluid.potion.*
		// tmp/gregtech.lang:699-845 + the residual rows), poison is the one hand row (毒液,
		// no S:fluid.poison dump face — the honest-default registration); the keys ride the
		// SAME GTFluids.FOOD_B2_SPECS derivation the en walk and the FluidType descriptionIds use.
		for (GTFluids.AquaFluidSpec tSpec : GTFluids.FOOD_B2_SPECS) {
			addDirect("fluid.gt6." + tSpec.name());
		}
		// task p33-food-tail: the 10 card-block-outside drink-fluid display names (the
		// golden-apple brews :607-610 + the coffee family :637-642) — the dump carries 9
		// faces (S:fluid.potion.goldenapplejuice=金苹果汁 tmp/gregtech.lang:725, goldencider
		// :726 金苹果酒, idunsapplejuice :734 伊顿苹果汁, notchesbrew :758 炖Notch,
		// darkcoffee :713 清咖啡, darkcafeaulait :711 欧蕾黑咖啡, cafeaulait :702 欧蕾咖啡,
		// laitaucafe :747 法式牛奶咖啡, darkchocolatemilk :712 苦味巧克力牛奶); plain
		// potion.coffee has no dump face (the 欧蕾咖啡 row implies the base) — hand row 咖啡;
		// the keys ride the SAME GTFluids.FOOD_TAIL_SPECS derivation the en walk and the
		// FluidType descriptionIds use.
		for (GTFluids.AquaFluidSpec tSpec : GTFluids.FOOD_TAIL_SPECS) {
			addDirect("fluid.gt6." + tSpec.name());
		}
		// task p29-w4-f1-chemicals + p31-qu-b-materials: the 34 chemical display names —
		// the dump carries every
		// face (S:fluid.liquid_extra_heavy_oil=超重油 tmp/gregtech.lang:388, :389-391 the
		// other oils, S:fluid.soulsandoil=灵魂沙油 :865, S:fluid.propane=丙烷 :817,
		// S:fluid.butane=丁烷 :120, S:fluid.propylene=丙烯 :821, S:fluid.ethylene=乙烯 :289,
		// S:fluid.methane=甲烷 :413, S:fluid.carbondioxide=二氧化碳 :127,
		// S:fluid.carbonmonoxide=一氧化碳 :128, S:fluid.hydrogen=氢气 :355,
		// S:fluid.nitrogen=氮 :658, S:fluid.oxygen=氧 :668, S:fluid.fluorine=氟 :301,
		// S:fluid.helium=氦 :328, S:fluid.neon=氖 :651, S:fluid.argon=氩 :54,
		// S:fluid.krypton=氪 :381, S:fluid.xenon=氙 :920, S:fluid.radon=氡 :828,
		// S:fluid.liquidoxygen=液氧 :392, S:fluid.heliumplasma=氦离子 :331,
		// S:fluid.nitrogenplasma=氮离子 :661; the isotope batch (p31-qu-b-materials)
		// S:fluid.deuterium=氘 :213, S:fluid.tritium=氚 :898, S:fluid.helium3=氦-3 :329,
		// S:fluid.molten.lithium6=熔融锂-6 :530, S:fluid.molten.beryllium7=熔融铍-7 :450,
		// S:fluid.molten.beryllium8=熔融铍-8 :451, S:fluid.molten.boron11=熔融硼-11 :459,
		// S:fluid.molten.carbon13=熔融碳-13 :467, S:fluid.molten.ancientdebris=熔融远古残骸
		// :434); the keys ride the SAME GTFluids.CHEMICAL_SPECS
		// derivation the en walk and the FluidType descriptionIds use. Values are hand rows
		// in the reference table.
		for (GTFluids.ChemicalFluidSpec tSpec : GTFluids.CHEMICAL_SPECS) {
			addDirect(tSpec.descriptionId());
		}
		// task p29-w4-hot-lube: the 20 hot-family display names — the 12 hot fluids + the 7
		// FM.Hot closure carriers + the F-2 lubricant; the dump carries all but one face
		// (S:fluid.ic2coolant=冷却液 tmp/gregtech.lang:362, S:fluid.ic2hotcoolant=热冷却液
		// :364, S:fluid.hotmoltensodium=热熔融钠 :347, S:fluid.hotmoltentin=热熔融锡 :348,
		// S:fluid.hotmoltenlicl=热熔融氯化锂 :346, S:fluid.hotheavywater=热重水 :344,
		// S:fluid.hotsemiheavywater=热半重水 :350, S:fluid.hottritiatedwater=热超重水 :351,
		// S:fluid.hotcarbondioxide=热二氧化碳 :341, S:fluid.hothelium=热氦 :345,
		// S:fluid.thoriumsalt=熔融钍盐 :890, S:fluid.ic2pahoehoelava=熔岩岩浆 :365,
		// S:fluid.blaze=烈焰粘浆 :104, S:fluid.molten.sodium=熔融钠 :596,
		// S:fluid.molten.tin=熔融锡 :614, S:fluid.heavywater=重水 :327,
		// S:fluid.semiheavywater=半重水 :853, S:fluid.tritiatedwater=超重水 :897,
		// S:fluid.lubricant=润滑油 :394; the lithium_chloride_molten display 熔融氯化锂 is
		// the one hand row following the molten.X=熔融X dump rule); the keys ride the SAME
		// GTFluids.HOT/CLOSURE/LUBRICANT tables the en walk uses.
		for (GTFluids.ChemicalFluidSpec tSpec : GTFluids.HOT_FLUID_SPECS) {
			addDirect(tSpec.descriptionId());
		}
		for (GTFluids.ChemicalFluidSpec tSpec : GTFluids.CLOSURE_FLUID_SPECS) {
			addDirect(tSpec.descriptionId());
		}
		for (GTFluids.ChemicalFluidSpec tSpec : GTFluids.LUBRICANT_FLUID_SPECS) {
			addDirect(tSpec.descriptionId());
		}
		// task p31-qu-a-foundation: the 3 QU-matter display names (chargedmatter/
		// neutralmatter/enderpearl_molten) — no upstream zh dump face exists for these
		// fluids (the 1.7.10 zh assets carry no S:fluid.chargedmatter row to borrow); all
		// three are hand rows in the reference table (带电物质/中性物质 the physics-standard
		// charged/neutral pairing, 熔融末影珍珠 the molten.<mat>=熔融X rule over the vanilla
		// pearl name); the keys ride the SAME GTFluids.QU_FLUID_SPECS table the en walk uses.
		for (GTFluids.ChemicalFluidSpec tSpec : GTFluids.QU_FLUID_SPECS) {
			addDirect(tSpec.descriptionId());
		}
		// task p26-c-foam-fluid-refill: the base + the 32 C-Foam display names — the dump
		// carries all 33 faces (S:fluid.ic2constructionfoam=建筑泡沫 tmp/gregtech.lang:361,
		// S:fluid.cfoam.* :130-161); the keys ride the SAME GTFluids.cfoamName/
		// cfoamOwnedName derivation the en walk and the FluidType descriptionIds use.
		// Values are hand rows in the reference table.
		addDirect("fluid.gt6.cfoam");
		for (int i = 0; i < 16; i++) {
			addDirect("fluid.gt6." + GTFluids.cfoamName(i));
		}
		for (int i = 0; i < 16; i++) {
			addDirect("fluid.gt6." + GTFluids.cfoamOwnedName(i));
		}
		// task p26-c-foam-block-family + p28-cfoam-lang-key: the 5 C-Foam BLOCK display names
		// — no upstream zh dump face exists for the modern block ids (the 1.7.10 block names
		// rode the meta ladder); all five are hand rows in the reference table (the dried
		// full block shares the fluid's 建筑泡沫 face, the fresh form prefixes 新鲜, the
		// slabs append 台阶; the owned carrier joins at p28 as 强化建筑泡沫 — the user
		// ruling 2026-09-12: the strengthened-spray foam must carry 强化, matching the en
		// "Advanced C-Foam" face).
		addDirect("block.gt6.cfoam_fresh");
		addDirect("block.gt6.cfoam");
		addDirect("block.gt6.cfoam_owned");
		addDirect("block.gt6.cfoam_fresh_slab");
		addDirect("block.gt6.cfoam_slab");
		// the P22 spray-can domain (no upstream face anywhere — all hand)
		addDirect("item.gt6.spray_can_empty");
		addDirect("item.gt6.spray_paint_black");
		addDirect("item.gt6.spray_paint_blue");
		addDirect("item.gt6.spray_paint_brown");
		addDirect("item.gt6.spray_paint_cyan");
		addDirect("item.gt6.spray_paint_gray");
		addDirect("item.gt6.spray_paint_green");
		addDirect("item.gt6.spray_paint_light_blue");
		addDirect("item.gt6.spray_paint_light_gray");
		addDirect("item.gt6.spray_paint_lime");
		addDirect("item.gt6.spray_paint_magenta");
		addDirect("item.gt6.spray_paint_orange");
		addDirect("item.gt6.spray_paint_pink");
		addDirect("item.gt6.spray_paint_purple");
		addDirect("item.gt6.spray_paint_red");
		addDirect("item.gt6.spray_paint_remover");
		addDirect("item.gt6.spray_paint_white");
		addDirect("item.gt6.spray_paint_yellow");
		addDirect("gt6.spraycan.decolor");
		addDirect("gt6.spraycan.paint");
		addDirect("gt6.spraycan.remaining");
		// the five backfill materials (review/absent dump rows cannot ride the family join;
		// superconductor = the TeamNED double-source cross)
		addDirect("gt6.material.breeze");
		addDirect("gt6.material.carminite");
		addDirect("gt6.material.fireleaf");
		addDirect("gt6.material.golden_amber");
		addDirect("gt6.material.superconductor");
		// the two new tabs
		addDirect("itemGroup.gt6.billet");
		addDirect("itemGroup.gt6.spray_cans");
	}

	/**
	 * The B2 stone-variant composed-display units (task p20-i18n-compose-rows): the 16
	 * {@code gt6.stone.variant.<snake>} position-param templates the
	 * {@code GTStoneBlock.getName} compose fills (the stone-name slot rides the
	 * gt6.material.* small units, zero new material debt). Wording = the dump's
	 * gt.stone.andesite.N family split (tmp/gregtech.lang:15246-15262).
	 */
	private void addStoneVariantUnits() {
		for (gregtech6.block.stone.StoneVariant tVariant : gregtech6.block.stone.StoneVariant.VALUES) {
			addDirect(tVariant.key());
		}
	}

	/**
	 * The static storage batch display rows (task p26-storage-static-batch): one hand row
	 * per GT6StaticStorages row (the kind faces 柜/抽屉/保险箱/书架/瓶箱; the metal words
	 * reuse the row.mat family, the plank words are hand rows of the vanilla-planks subset).
	 */
	private void addStaticStorageUnits() {
		for (gregtech6.registry.GT6StaticStorages.StaticRow tRow : gregtech6.registry.GT6StaticStorages.ROWS) {
			addDirect("block.gt6." + tRow.path());
		}
	}

	/**
	 * The B2 rows composed-display units (task p20-i18n-compose-rows): every family template
	 * + small unit the rows composes consume, walked from the SAME row tables and key
	 * derivations the en walk uses (the mirrors cannot drift on the KEY face; the VALUE face
	 * is the hand layer in the reference table). The atomic rows (brick burning box, heat
	 * transmitter, the two wood gearboxes) ride the same hand rows as their en literals.
	 */
	private void addRowDomainUnits() {
		// a word shared by several families is ONE unit key — dedup like the en walk's
		// addRowMatUnit (duplicate add would be a hard failure on the recording face)
		java.util.Set<String> tEmitted = new java.util.HashSet<>();
		
		addDirect(gregtech6.registry.GT6Kinetics.AXLE_DISPLAY_KEY);
		for (int tSize = 0; tSize < gregtech6.registry.GT6Kinetics.AXLE_SIZE_NAMES.length; tSize++) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Kinetics.axleSizeUnitKey(tSize));
		}
		for (gregtech6.registry.GT6Kinetics.AxleSpec tSpec : gregtech6.registry.GT6Kinetics.AXLE_SPECS) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Kinetics.axleMatUnitKey(tSpec));
		}
		// steam engines: the two templates + the row-material units
		addDirect(gregtech6.registry.GT6Kinetics.STEAM_DISPLAY_KEY);
		addDirect(gregtech6.registry.GT6Kinetics.STEAM_DISPLAY_STRONG_KEY);
		for (gregtech6.registry.GT6Kinetics.SteamEngineRow tRow : gregtech6.registry.GT6Kinetics.STEAM_ENGINES) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Kinetics.steamMatUnitKey(tRow));
		}
		// diesel: the template + the row-material units
		addDirect(gregtech6.registry.GT6Kinetics.DIESEL_DISPLAY_KEY);
		for (gregtech6.registry.GT6Kinetics.DieselSpec tSpec : gregtech6.registry.GT6Kinetics.DIESEL_SPECS) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Kinetics.dieselMatUnitKey(tSpec));
		}
		// burning boxes: the four templates + three family words + the row-material units
		addDirect(gregtech6.registry.GT6BurningBoxes.DISPLAY_KEY);
		addDirect(gregtech6.registry.GT6BurningBoxes.DISPLAY_DENSE_KEY);
		addDirect(gregtech6.registry.GT6BurningBoxes.DISPLAY_FLUIDBED_KEY);
		addDirect(gregtech6.registry.GT6BurningBoxes.DISPLAY_FLUIDBED_DENSE_KEY);
		addDirect(gregtech6.registry.GT6BurningBoxes.FAMILY_SOLID_UNIT_KEY);
		addDirect(gregtech6.registry.GT6BurningBoxes.FAMILY_LIQUID_UNIT_KEY);
		addDirect(gregtech6.registry.GT6BurningBoxes.FAMILY_GAS_UNIT_KEY);
		for (gregtech6.registry.GT6BurningBoxes.BurningBoxRow tRow : gregtech6.registry.GT6BurningBoxes.allRows()) {
			addRowUnit(tEmitted, gregtech6.registry.GT6BurningBoxes.matUnitKeyOf(tRow));
		}
		addDirect("block.gt6.brick_burning_box"); // the atomic Brick row (the whole-string key on both faces)
		// boilers: the two templates + the row-material units
		addDirect(gregtech6.registry.GT6Boilers.DISPLAY_KEY);
		addDirect(gregtech6.registry.GT6Boilers.DISPLAY_STRONG_KEY);
		for (gregtech6.registry.GT6Boilers.BoilerRow tRow : gregtech6.registry.GT6Boilers.allRows()) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Boilers.matUnitKeyOf(tRow));
		}
		// machine tiers: the template + three machine words (task p27-machine-energy-display-fix:
		// the tier slot rides the Kinetic_T material word — the bronze/steel/titanium/
		// tungstensteel gt6.row.mat units are joined by the W1 Kinetic trio walk below,
		// and the ordinal gt6.row.tier.* units are RETIRED)
		addDirect(gregtech6.registry.GTMachines.MACHINE_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_SHREDDER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_CRUSHER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_LATHE_UNIT_KEY);
		// oven (task p27-oven-heat-t-ladder, rebased over p27-machine-energy-display-fix —
		// the ordinal gt6.row.tier.* walk is retired upstream-side): the family template over
		// the Heat_T word set — the steel/invar/titanium/tungsten_carbide units already ride
		// the dryer/distillery walk's dedup above, only the template is new (the retired
		// atomic block.gt6.oven joined the composed face, the upstream name column
		// "Oven ("+Heat_T local+")")
		addDirect(gregtech6.registry.GTMachines.OVEN_DISPLAY_KEY);
		// dryer/distillery: the two family templates + their row-material units
		addDirect(gregtech6.registry.GTMachines.DRYER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.DISTILLERY_DISPLAY_KEY);
		for (java.util.List<gregtech6.block.GTBasicMachineBlock.MachineRow> tRows
				: java.util.List.of(gregtech6.registry.GTMachines.DRYER_ROWS, gregtech6.registry.GTMachines.DISTILLERY_ROWS)) {
			for (gregtech6.block.GTBasicMachineBlock.MachineRow tRow : tRows) {
				addRowUnit(tEmitted, "gt6.row.mat." + tRow.matSlug());
			}
		}
		// canner (task p24-canner-machine): the family template + the VN voltage-row units
		addDirect(gregtech6.registry.GTMachines.CANNER_DISPLAY_KEY);
		for (gregtech6.block.GTBasicMachineBlock.MachineRow tRow : gregtech6.registry.GTMachines.CANNER_ROWS) {
			addRowUnit(tEmitted, "gt6.row.mat." + tRow.matSlug());
		}
		// item pipes (task p26-pipe-item): the six variant templates + the row-material
		// units (brass exists; constantan/cobalt_brass join) + the category tab (dump :17993)
		addDirect(gregtech6.registry.GTItemPipes.DISPLAY_KEY_PREFIX + "medium");
		addDirect(gregtech6.registry.GTItemPipes.DISPLAY_KEY_PREFIX + "large");
		addDirect(gregtech6.registry.GTItemPipes.DISPLAY_KEY_PREFIX + "huge");
		addDirect(gregtech6.registry.GTItemPipes.DISPLAY_KEY_PREFIX + "restrictive_medium");
		addDirect(gregtech6.registry.GTItemPipes.DISPLAY_KEY_PREFIX + "restrictive_large");
		addDirect(gregtech6.registry.GTItemPipes.DISPLAY_KEY_PREFIX + "restrictive_huge");
		for (gregtech6.registry.GTItemPipes.ItemPipeMaterial tPipeMat : gregtech6.registry.GTItemPipes.MATERIALS) {
			addRowUnit(tEmitted, tPipeMat.unitKey());
		}
		addDirect("itemGroup.gt6.item_pipes");
		// W1 Kinetic trio (task p26-w1-sifter-compressor-wiremill): the three family
		// templates (the unit-key carrier) + the Kinetic_T row-material units
		addDirect(gregtech6.registry.GTMachines.MACHINE_SIFTER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_COMPRESSOR_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_WIREMILL_UNIT_KEY);
		for (java.util.List<gregtech6.block.GTBasicMachineBlock.MachineRow> tKineticRows
				: java.util.List.of(gregtech6.registry.GTMachines.SIFTER_ROWS, gregtech6.registry.GTMachines.COMPRESSOR_ROWS, gregtech6.registry.GTMachines.WIREMILL_ROWS)) {
			for (gregtech6.block.GTBasicMachineBlock.MachineRow tRow : tKineticRows) {
				addRowUnit(tEmitted, "gt6.row.mat." + tRow.matSlug());
			}
		}
		// press + extruder (task p26-w1-press-extruder-molds): the family templates + the
		// :101-104 unit words (the T1 Low Heat face keeps the tier word — en "Low Heat
		// Extruder (%s)"; task p28-lang-batch1-fix reverted the batch1 low-confidence words
		// to the community 压力成型机/压模器 forms, with the low-heat rows as 低温压模器)
		addDirect(gregtech6.registry.GTMachines.PRESS_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.EXTRUDER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.EXTRUDER_LOW_HEAT_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_PRESS_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_EXTRUDER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_EXTRUDER_LOW_HEAT_UNIT_KEY);
		for (java.util.List<gregtech6.block.GTBasicMachineBlock.MachineRow> tRows
				: java.util.List.of(gregtech6.registry.GTMachines.PRESS_ROWS, gregtech6.registry.GTMachines.EXTRUDER_ROWS)) {
			for (gregtech6.block.GTBasicMachineBlock.MachineRow tRow : tRows) {
				addRowUnit(tEmitted, "gt6.row.mat." + tRow.matSlug());
			}
		}
		// p28 ULV ladder (task p28-c-ulv-machine-ladder): the three new one-slot templates
		// + the ULV row-material units (any_wood = the Kinetic_T[0] word 木, dump
		// gt.material.AnyWood; ulv = the VN[0] id, CS.java:154 — the tsv hand rows carry
		// both) + the rollingmill family template
		addDirect(gregtech6.registry.GTMachines.MACHINE_SHREDDER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_CRUSHER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_ROLLING_MILL_UNIT_KEY);
		// the roll ladders (task p29-w1-kinetic-roll-ladder): the three new one-slot
		// templates (the RU rollingmill rows share the rollingmill template above) —
		// the dump-verbatim words 辊弯机/辊压成型机/多辊式轧机 (tmp/gregtech.lang:11502-11515,
		// gt.multitileentity.20121-20124 / 20131-20134 / 20141-20144)
		addDirect(gregtech6.registry.GTMachines.MACHINE_ROLL_BENDER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_ROLL_FORMER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_CLUSTER_MILL_UNIT_KEY);
		for (java.util.List<gregtech6.block.GTBasicMachineBlock.MachineRow> tRollRows
				: java.util.List.of(gregtech6.registry.GTMachines.ROLLINGMILL_RU_ROWS, gregtech6.registry.GTMachines.ROLL_BENDER_ROWS,
						gregtech6.registry.GTMachines.ROLL_FORMER_ROWS, gregtech6.registry.GTMachines.CLUSTER_MILL_ROWS)) {
			for (gregtech6.block.GTBasicMachineBlock.MachineRow tRow : tRollRows) {
				addRowUnit(tEmitted, "gt6.row.mat." + tRow.matSlug());
			}
		}
		// eu-hu families (task p29-w1-eu-hu-families): the seven family templates — the
		// Mixer rides the Kinetic_T material-word slot (the W1 trio walk above already
		// emits bronze/steel/titanium/tungstensteel), the five Electric* ladders the VN
		// voltage words (the canner walk emits lv/mv/hv/ev), the Fermenter the atomic
		// single-variant row; the zh words are the upstream dump verbatim
		// (gt.multitileentity.20181/20351/20361/20371/20581/20591/22003)
		addDirect(gregtech6.registry.GTMachines.MACHINE_MIXER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.ELECTRIC_MIXER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.ELECTRIC_LOOM_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.ELECTRIC_SIFTER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.BOXINATOR_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.UNBOXINATOR_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.FERMENTER_DISPLAY_KEY);
		// eu-special families (task p29-w2-eu-special): the three family templates — the
		// Autocrafter/LightningProcessor ladders ride the VN voltage words (lv..iv all
		// emitted: the canner walk + the standalone iv rung above), the Laminator the
		// Heat_T material words (the oven/dryer walks emit them); the zh words are the
		// upstream dump verbatim (gt.multitileentity.20341/20501/20391)
		addDirect(gregtech6.registry.GTMachines.AUTOCRAFTER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.LIGHTNING_PROCESSOR_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.LAMINATOR_DISPLAY_KEY);
		// hu-tu piggyback (task p29-w2-hu-tu-piggyback): the seven family templates — the
		// two Crackers and the Loom ride the material-word slot (the Heat_T/Kinetic row
		// words are the walks above), the TU four are the atomic single-variant rows; the
		// zh words are the upstream dump verbatim
		// (gt.multitileentity.20491-20494/20481-20484/22000/22001/22002/22004/20211-20214)
		addDirect(gregtech6.registry.GTMachines.MACHINE_STEAM_CRACKER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_CATALYTIC_CRACKER_UNIT_KEY);
		// task p34-machines-burner-plantalyzer — the two family templates (the dump faces
		// 燃烧反应室 gt.multitileentity.20521-20524 / 植物分析仪 :11705-11709, the tsv
		// direct band; the tier slots ride the EXISTING gt6.row.mat words — bronze/steel/
		// titanium/tungstensteel and lv..iv)
		addDirect(gregtech6.registry.GTMachines.MACHINE_BURNER_MIXER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_PLANTALYZER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_LOOM_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.COAGULATOR_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.GENERIFIER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.BATH_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.AUTOCLAVE_DISPLAY_KEY);
		// heat-smelter families (task p29-w3-heat-smelter): the Smelter rides the
		// material-word slot (the Heat_T row words are the walks above), the Melter is
		// the atomic single-variant row; the zh words are the upstream dump verbatim
		// (gt.multitileentity.20241-20244 液化炉, 22010 "Melter" ASCII → the hand row 熔化炉)
		addDirect(gregtech6.registry.GTMachines.MACHINE_SMELTER_UNIT_KEY);
		// p34 machine families (task p34-machines-bumblelyzer-crucible): the Bumblelyzer
		// rides the voltage-word slot, the Crystallisation Crucible the Heat_T material-word
		// slot; the zh words are the upstream dump verbatim
		// (gt.multitileentity.20541-20545 膜翅目昆虫分析仪, 20251-20254 结晶器)
		addDirect(gregtech6.registry.GTMachines.MACHINE_BUMBLELYZER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_CRYSTALLISATION_UNIT_KEY);
		addDirect("block.gt6.large_heat_exchanger"); // task p29-w3-heat-smelter — the HEX (the dump word 大型热交换器, gt.multitileentity.17197)
		addDirect(gregtech6.registry.GTMachines.MELTER_DISPLAY_KEY);
		// the fermenter's stainless_steel row word (the dump face the attachment walk
		// already carries — emitted here so the row walk stays self-contained)
		addRowUnit(tEmitted, "gt6.row.mat.stainless_steel");		for (java.util.List<gregtech6.block.GTBasicMachineBlock.MachineRow> tUlvRows
				: java.util.List.of(gregtech6.registry.GTMachines.CANNER_ULV_ROWS, gregtech6.registry.GTMachines.SIFTER_ULV_ROWS,
						gregtech6.registry.GTMachines.WIREMILL_ULV_ROWS, gregtech6.registry.GTMachines.SHREDDER_ULV_ROWS,
						gregtech6.registry.GTMachines.CRUSHER_ULV_ROWS, gregtech6.registry.GTMachines.ROLLINGMILL_ROWS)) {
			for (gregtech6.block.GTBasicMachineBlock.MachineRow tRow : tUlvRows) {
				addRowUnit(tEmitted, "gt6.row.mat." + tRow.matSlug());
			}
		}
		// the p29 W2 5-tier voltage rung (task p29-w2-energy-types-5tier ②): the VN[5] word
		// "IV" (CS.java:154 — the card gloss said EV, refuted by the array and by ev already
		// being T4's word; the GTMachines.EV_TIER_INPUTS doc carries the erratum) — emitted
		// standalone until the card-② 5-tier rows give it a row walk to ride
		addRowUnit(tEmitted, "gt6.row.mat.iv");
		// P29 W1 process families (task p29-w1-kinetic-process-ladder): the six family
		// templates + the Kinetic_T row words (the trio walk above emits them; the tsv
		// hand rows carry the dump-mte words 圆锯/榨汁机/离心机/洗矿厂/砂轮/水压清洗机
		// from the :1318-1321/:1324-1327/:1330-1333/:1464-1467/:1589-1592/:1615-1618
		// upstream name columns over the Kinetic_T locals)
		// P29 W2 exotic-energy families (task p29-w2-exotic-energy): the six family
		// templates — the Polarizer/Magnetic Separator ride the material-word slot (the
		// Electric_T rung words; galvanized_steel/aluminium join the tsv hand rows, the
		// stainless_steel/chromium/titanium words ride the existing rows), the Laser
		// Engraver / Laser Welder / Freezer / Cryo Mixer the LITERAL tier-word slot
		// (gt6.row.mat.t1..t5 — the dump words 电磁偏振器/磁选机/激光刻蚀机/激光焊接器/
		// 冷冻机/低温搅拌机, gt.multitileentity.20221/20301/20321/20331/20561/20571)
		addDirect(gregtech6.registry.GTMachines.MACHINE_POLARIZER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_MAGNETIC_SEPARATOR_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_LASER_ENGRAVER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_LASER_WELDER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_FREEZER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_CRYO_MIXER_UNIT_KEY);
		// task p31-massfab — the small Massfab family template + the large controller
		// (the Loader :1241/:1542-1546 name columns; zh hand words 大型物质制造机/物质制造机)
		addDirect("block.gt6.large_massfab");
		addDirect("block.gt6.logistics_core"); // task p32-logistics-lv3 — the dump mte multiblock.logisticscore row 物流核心 (zh_cn_ref.tsv :8146)
		addDirect("block.gt6.fusion_reactor"); // task p31-fusion — the Loader :1242 name column (zh: the dump :11253 row)
		addDirect(gregtech6.registry.GTMachines.MACHINE_MASSFAB_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_MOLECULAR_SCANNER_UNIT_KEY); // task p32-qu-scanner-replicator — the dump :11662 name column (分子扫描仪)
		addDirect(gregtech6.registry.GTMachines.MACHINE_REPLICATOR_UNIT_KEY); // task p32-qu-scanner-replicator — the dump :11664-11666 name column (物质复制器)
		for (java.util.List<gregtech6.block.GTBasicMachineBlock.MachineRow> tExoticRows
				: java.util.List.of(gregtech6.registry.GTMachines.POLARIZER_ROWS, gregtech6.registry.GTMachines.MAGNETIC_SEPARATOR_ROWS,
						gregtech6.registry.GTMachines.LASER_ENGRAVER_ROWS, gregtech6.registry.GTMachines.LASER_WELDER_ROWS,
						gregtech6.registry.GTMachines.FREEZER_ROWS, gregtech6.registry.GTMachines.CRYO_MIXER_ROWS)) {
			for (gregtech6.block.GTBasicMachineBlock.MachineRow tRow : tExoticRows) {
				addRowUnit(tEmitted, "gt6.row.mat." + tRow.matSlug());
			}
		}
		addDirect(gregtech6.registry.GTMachines.MACHINE_BUZZSAW_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_SQUEEZER_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_CENTRIFUGE_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_SLUICE_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_SANDING_UNIT_KEY);
		addDirect(gregtech6.registry.GTMachines.MACHINE_PRESSURE_WASHER_UNIT_KEY);
		for (java.util.List<gregtech6.block.GTBasicMachineBlock.MachineRow> tProcessRows
				: java.util.List.of(gregtech6.registry.GTMachines.BUZZSAW_ROWS, gregtech6.registry.GTMachines.SQUEEZER_ROWS,
						gregtech6.registry.GTMachines.CENTRIFUGE_ROWS, gregtech6.registry.GTMachines.SLUICE_ROWS,
						gregtech6.registry.GTMachines.SANDING_ROWS, gregtech6.registry.GTMachines.PRESSURE_WASHER_ROWS)) {
			for (gregtech6.block.GTBasicMachineBlock.MachineRow tRow : tProcessRows) {
				addRowUnit(tEmitted, "gt6.row.mat." + tRow.matSlug());
			}
		}
		// eu-core families (task p29-w2-eu-core-5tier): the five 5-tier templates — the
		// voltage-word slot over the FULL VN[1..5] ladder (the row walk emits lv/mv/hv/ev
		// already covered by the canner walk AND the fifth word iv, the standalone card-①
		// emission above now riding its rows — duplicates are the set's idempotent face);
		// the zh words are the upstream dump verbatim (电解器/流体灌装机/打印机/扫描仪/
		// 切片器, gt.multitileentity.20091/20261/20271/20281/20381 — the Scanner (Visuals)
		// en comma form carries no visuals word in the dump column)
		addDirect(gregtech6.registry.GTMachines.ELECTROLYZER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.INJECTOR_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.PRINTER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.SCANNER_VISUALS_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMachines.SLICER_DISPLAY_KEY);
		for (java.util.List<gregtech6.block.GTBasicMachineBlock.MachineRow> tEuCoreRows
				: java.util.List.of(gregtech6.registry.GTMachines.ELECTROLYZER_ROWS, gregtech6.registry.GTMachines.INJECTOR_ROWS,
						gregtech6.registry.GTMachines.PRINTER_ROWS, gregtech6.registry.GTMachines.SCANNER_VISUALS_ROWS,
						gregtech6.registry.GTMachines.SLICER_ROWS)) {
			for (gregtech6.block.GTBasicMachineBlock.MachineRow tRow : tEuCoreRows) {
				addRowUnit(tEmitted, "gt6.row.mat." + tRow.matSlug());
			}
		}
		// storage hoppers (task p26-storage-hopper-family): the two kind templates over the
		// bronze/steel row words (the boiler walk emits them; the tsv hand rows carry the
		// 料斗/队列料斗 wording since task p28-lang-batch1-fix — funnel keeps 漏斗)
		addDirect(gregtech6.registry.GT6Hoppers.DISPLAY_KEY);
		addDirect(gregtech6.registry.GT6Hoppers.DISPLAY_QUEUE_KEY);
		for (gregtech6.registry.GT6Hoppers.HopperRow tRow : gregtech6.registry.GT6Hoppers.ROWS) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Hoppers.matUnitKeyOf(tRow));
		}
		// large boiler + dense wall: the templates + the row-material units
		addDirect(gregtech6.registry.GTMultiBlocks.LARGE_BOILER_DISPLAY_KEY);
		addDirect(gregtech6.registry.GTMultiBlocks.DENSE_WALL_DISPLAY_KEY);
		for (gregtech6.registry.GTMultiBlocks.LargeBoilerRow tRow : gregtech6.registry.GTMultiBlocks.LARGE_BOILER_ROWS) {
			addRowUnit(tEmitted, gregtech6.registry.GTMultiBlocks.boilerMatUnitKeyOf(tRow));
		}
		for (gregtech6.registry.GTMultiBlocks.MultiblockPartRow tRow : gregtech6.registry.GTMultiBlocks.WALL_ROWS) {
			addRowUnit(tEmitted, gregtech6.registry.GTMultiBlocks.wallMatUnitKeyOf(tRow));
		}
		addDirect("block.gt6.heat_transmitter"); // the atomic transmitter (the whole-string key)
		// lightning rod (task p24-lightning-rod): the controller + the three atomic parts +
		// the addToolTips replay keys (the dump rows :15141/:11359/:11380/:11389/:17758-17766,
		// the hand layer in the reference table; the KEY face mirrors the en addMultiBlocks tail)
		addDirect("block.gt6.multiblock_lightning_rod");
		addDirect("block.gt6.machine_wall_tungsten");
		addDirect("block.gt6.niobium_titanium_coil");
		addDirect("block.gt6.lightning_rod");
		// task p29-w3-nbtdesign-parts — the part-family expansion: the metal-wall template
		// over the existing row words + the atomic names (the dump mte words, verbatim)
		addDirect(gregtech6.registry.GTMultiBlocks.PartRow.METAL_WALL_DISPLAY_KEY);
		for (gregtech6.registry.GTMultiBlocks.PartRow tRow : gregtech6.registry.GTMultiBlocks.NEW_PART_ROWS) {
			if (!tRow.metalWall()) {
				addDirect("block.gt6." + tRow.path());
			}
		}
		// task p29-w3-tank-valves — the 25 valve rows: the size+material compose templates
		// (CJK 免空格 gluing, the dump word order 小型/大型 + 材质 + 储罐主阀) + the size
		// words + the wood unit; the metal material words are the EXISTING dense-wall units
		addDirect(gregtech6.registry.GT6Tanks.TANK_VALVE_DISPLAY_KEY);
		addDirect(gregtech6.registry.GT6Tanks.TANK_VALVE_WOOD_DISPLAY_KEY);
		addDirect(gregtech6.registry.GT6Tanks.WOOD_UNIT_KEY);
		addDirect(gregtech6.registry.GT6Tanks.SIZE_SMALL);
		addDirect(gregtech6.registry.GT6Tanks.SIZE_SMALL_DENSE);
		addDirect(gregtech6.registry.GT6Tanks.SIZE_LARGE);
		addDirect(gregtech6.registry.GT6Tanks.SIZE_LARGE_DENSE);
		// task p29-w3-turbine-dynamo — the twelve turbine/dynamo controller names (the
		// Loader :1254-1257/:1259-1262/:1264-1267 name column; the hand layer in the
		// reference table — the material words reuse the dump mte translations)
		for (gregtech6.registry.GT6Turbines.SteamTurbineRow tRow : gregtech6.registry.GT6Turbines.STEAM_ROWS) {
			addDirect("block.gt6." + tRow.path());
		}
		for (gregtech6.registry.GT6Turbines.GasTurbineRow tRow : gregtech6.registry.GT6Turbines.GAS_ROWS) {
			addDirect("block.gt6." + tRow.path());
		}
		for (gregtech6.registry.GT6DynamoHousings.DynamoRow tRow : gregtech6.registry.GT6DynamoHousings.DYNAMO_ROWS) {
			addDirect("block.gt6." + tRow.path());
		}
		// task p29-w3-large-12 — the twelve large machines, the dump
		// gt.multitileentity.multiblock.{centrifuge..squeezer} column verbatim
		// (tmp/gregtech.lang :15125-15138; the coagulator dump slot is EMPTY upstream,
		// the composed 大型凝结器阵列 rides the W2 凝结器 word; the Array tail renders
		// the upstream "Large Coagulator Array" name column)
		add("block.gt6.large_centrifuge", "大型离心机");
		add("block.gt6.large_electrolyzer", "大型电解机");
		add("block.gt6.large_coagulator", "大型凝结器阵列");
		add("block.gt6.large_autoclave", "大型高压釜");
		add("block.gt6.large_bath", "大型浸洗器");
		add("block.gt6.large_batch_mixer", "大型搅拌机");
		add("block.gt6.large_fermenter", "大型发酵室");
		add("block.gt6.large_electric_oven", "大型电炉");
		add("block.gt6.large_sluice", "大型洗矿厂");
		add("block.gt6.large_crusher", "大型破碎机");
		add("block.gt6.large_shredder", "大型研磨机");
		add("block.gt6.large_squeezer", "大型榨汁机");
		// task p31-implosion / p32-hygiene-lang-assets — the Implosion Compressor (the
		// Loader :1228 row). dump-first corrected p32: the upstream zh dump reads
		// 聚爆压缩机 (tmp/gregtech.lang:15140 gt.multitileentity.multiblock.implosioncompressor
		// and :15204 gt.recipe.implosioncompressor; the reference table agrees,
		// zh_cn_ref.tsv:8134) — the earlier 爆破压缩机 (= "blasting", a different word)
		// was a hand-layer slip, not a dump face.
		add("block.gt6.implosion_compressor", "聚爆压缩机");
		// task p31-graagg — the Von da Graagg (the Loader :1280 row; hand zh — the upstream
		// dump carries zero Graagg rows, the transliteration keeps the "Generator" face of
		// the name column like the en row)
		add("block.gt6.von_da_graagg", "冯·达·格拉格发电机");
		addDirect(gregtech6.block.multiblock.GTLightningRodBlock.Item.KEY_STRUCTURE);
		for (int i = 1; i <= 9; i++) {
			addDirect(String.format(gregtech6.block.multiblock.GTLightningRodBlock.Item.KEY_LINE, i));
		}
		addDirect(gregtech6.block.multiblock.GTLightningRodBlock.Item.KEY_ENERGY);
		addDirect(gregtech6.block.multiblock.GTLightningRodBlock.Item.KEY_CAPACITY);
		// attachments: the two family templates + the attachment material words
		addDirect(gregtech6.registry.GT6Attachments.TAP_DISPLAY_KEY);
		addDirect(gregtech6.registry.GT6Attachments.FUNNEL_DISPLAY_KEY);
		for (gregtech6.registry.GT6Attachments.AttachmentRow tRow : gregtech6.registry.GT6Attachments.ROWS) {
			addRowUnit(tEmitted, gregtech6.registry.GT6Attachments.matUnitKeyOf(tRow));
		}
		// the two wood gearboxes (the atomic attachment extras, the Loader :1668/:1669 rows)
		addDirect("block.gt6.gearbox");
		addDirect("block.gt6.transformer_rotation");
	}

	/** Dedup across the row-family walks (the en addRowMatUnit mirror). */
	private void addRowUnit(java.util.Set<String> aEmitted, String aKey) {
		if (aEmitted.add(aKey)) addDirect(aKey);
	}

	/**
	 * The p26 mold/crucible/faucet chain zh faces (task p27-lang-fix-batch2, the ledger §6
	 * zh gap: the 70 keys the en chain — {@code GT6CrucibleDatagen.Lang} + the
	 * {@code GT6MoldDatagen.Lang} tail — emits with no zh face). Every key mirrors the en
	 * derivation from the SAME registry rows: the three smeltery display keys
	 * ({@code gt6.row.crucible.display.<path>} over {@link gregtech6.registry.GT6Crucibles#ROWS}),
	 * the mold display + raw-clay pairs ({@code gt6.row.mold.display.<path>} /
	 * {@code item.gt6.<path>_raw} over {@link gregtech6.registry.GT6Molds#ROWS} + the ceramic
	 * blank + {@link gregtech6.registry.GT6Molds#CERAMIC_ROWS}), the faucet template + material
	 * words ({@link gregtech6.registry.GT6Molds#FAUCET_DISPLAY_KEY} +
	 * {@link gregtech6.registry.GT6Molds#faucetMatUnitKeyOf} over {@link gregtech6.registry.GT6Molds#FAUCET_ROWS})
	 * and the raw faucet item. Values are hand rows in the reference table — dump-verbatim
	 * where the dump carries the face (粘土模具 (X) :10026-10092, 粘土模具 :10102,
	 * 粘土浇铸口 :10104, 熔炼坩埚 (材料) :10772/:10893/:10895, 坩埚浇铸口 (材料) :11199/:11224);
	 * the formed mold faces pair 粘土→陶瓷 on the dump's shape words (the upstream raw→fired
	 * hardening pair; the fired dump faces 模具 (X) already belong to the shape_extruder items).
	 */
	private void addMoldCrucibleUnits() {
		// the three smeltery rungs (the en GT6CrucibleDatagen.Lang:149-151 trio, walked)
		for (gregtech6.registry.GT6Crucibles.SmelteryRow tRow : gregtech6.registry.GT6Crucibles.ROWS) {
			addDirect("gt6.row.crucible.display." + tRow.path());
		}
		// the molds: the stone rung display, the ceramic blank display + raw, the 30
		// pre-carved shape pairs (the en GT6MoldDatagen.Lang:151-156 derivation)
		for (gregtech6.registry.GT6Molds.MoldRow tRow : gregtech6.registry.GT6Molds.ROWS) {
			addDirect("gt6.row.mold.display." + tRow.path());
		}
		addDirect("gt6.row.mold.display." + gregtech6.registry.GT6Molds.CERAMIC_BLANK_ROW.path());
		addDirect("item.gt6." + gregtech6.registry.GT6Molds.CERAMIC_BLANK_ROW.path() + "_raw");
		for (gregtech6.registry.GT6Molds.MoldRow tRow : gregtech6.registry.GT6Molds.CERAMIC_ROWS) {
			addDirect("gt6.row.mold.display." + tRow.path());
			addDirect("item.gt6." + tRow.path() + "_raw");
		}
		// the crucible faucets: the composed template + the two material words + the raw
		// clay faucet item (the en GT6MoldDatagen.Lang:158-161 faces; the raw key mirrors the
		// en literal — FAUCET_CERAMIC_RAW's registry path)
		addDirect(gregtech6.registry.GT6Molds.FAUCET_DISPLAY_KEY);
		for (gregtech6.registry.GT6Molds.FaucetRow tRow : gregtech6.registry.GT6Molds.FAUCET_ROWS) {
			addDirect(gregtech6.registry.GT6Molds.faucetMatUnitKeyOf(tRow));
		}
		addDirect("item.gt6.faucet_ceramic_raw");
	}

	/**
	 * The B1 wire-domain composed-display units (task p20-i18n-compose-wires): the five
	 * position-param templates the {@code GTWireBlock.displayNameOf} compose fills
	 * ({@code gt6.wire.display[.plain]} + the {@code gt6.wire.form.*} units), the two cover
	 * tier-ladder templates (the tier slot rides a plain literal — the CS.java:154 voltage
	 * numerals are proper nouns in BOTH locales, no small-unit keys) and the laser atomic
	 * exemption ({@code block.gt6.wire_laser}, the material-less family stays a whole-string
	 * key on both faces). All hand rows in the reference table — the zh wording evidence
	 * lives in the gen script's hand-layer comments. Emitted here so the en-side template
	 * walks (GT6EnUs.addElectricWires/addCovers) have their exact zh mirror: the composed
	 * zh wire names (e.g. "{@code 12×锡线缆}", "{@code 红色合金导线}") then cost ZERO new
	 * material translations on top of these eight units.
	 */
	private void addWireDomainUnits() {
		addDirect("gt6.wire.display");
		addDirect("gt6.wire.display.plain");
		addDirect("gt6.wire.form.wire");
		addDirect("gt6.wire.form.cable");
		addDirect("gt6.wire.form.wirelamp");
		addDirect("gt6.cover.conveyor.display");
		addDirect("gt6.cover.robot_arm.display");
		addDirect("gt6.cover.selector_tag.display"); // task p34-covers-gameplay-10 — the tag-selector ladder template
		addDirect("block.gt6.wire_laser");
	}

	/** The item + block prefix tab titles and the special MTE-category tabs (mirror of GT6EnUs.addTabTitles/addBlockTabTitles + the tab literals). */
	private void addTabTitles() {
		for (OreDictPrefix tPrefix : GTMaterialItems.tabPrefixes()) {
			addFromFamily("itemgroup", tPrefix.mNameInternal,
				"itemGroup.gt6." + MaterialPrefixItem.snakeCase(tPrefix.mNameInternal));
		}
		for (OreDictPrefix tPrefix : GTMaterialBlocks.tabPrefixes()) {
			addFromFamily("itemgroup", tPrefix.mNameInternal,
				"itemGroup.gt6." + MaterialPrefixItem.snakeCase(tPrefix.mNameInternal));
		}
		// the special tabs have no dump face (the 1.7.10 dump's itemGroup family holds prefix
		// tabs only) — their titles ride the hand rows, keyed by the same literals/constants
		// the en walk uses so the faces cannot drift
		addDirect("itemGroup.gt6.chests");
		addDirect("itemGroup.gt6.machines");
		addDirect("itemGroup.gt6.multiblocks");
		addDirect("itemGroup.gt6.fluid_containers");
		addDirect("itemGroup.gt6.fluid_pipes");
		addDirect("itemGroup.gt6.electric_wires");
		addDirect(GTWires.REDSTONE_TAB_TITLE_KEY);
		addDirect(GTWires.LASER_TAB_TITLE_KEY);
		addDirect(GT6Tools.TAB_TITLE_KEY);
		addDirect("itemGroup.gt6.food_cans"); // task p25-food-can-row0 — dump itemgroup gt.multiitem.cans 格雷科技: 罐头 (MultiItemCans.java:41 category label)
	}

	/**
	 * The ore tab title zh face (task p30-ore-3-datagen) — the SAME itemgroup family join as
	 * the roster walk above, keyed by {@link GT6OreBlocks#TAB_TITLE_KEY}: the ore prefixes
	 * are not in the tabPrefixes() roster (upstream PrefixBlockItem.java:62-67 hides them),
	 * so the roster loop cannot carry the key; the dump row
	 * {@code itemgroup/oreVanillastone = 矿石} does (auto status, the same emit band).
	 */
	private void addOreTabTitle() {
		addFromFamily("itemgroup", GT6OreBlocks.TAB_FAMILY.prefix().mNameInternal, GT6OreBlocks.TAB_TITLE_KEY);
	}

	/** Only the hand-translated in-use prefix templates (mirror of GT6EnUs.addPrefixTemplates over OP.VALUES). */
	private void addPrefixTemplates() {
		Set<String> tSeen = new HashSet<>();
		for (OreDictPrefix tPrefix : OreDictPrefix.VALUES) {
			String tKey = "gt6.tagprefix." + MaterialPrefixItem.snakeCase(tPrefix.mNameInternal);
			if (!tSeen.add(tKey)) continue; // same snake_case-collision guard as the en walk
			addDirect(tKey);
		}
	}

	/**
	 * The material small units: the shared {@link GT6EnUs#materialWalkEmittedKeys} seam (alias
	 * merge, first mID wins) joined against the dump family — the seam's Map form carries the
	 * merged material identity the mNameInternal family lookup needs (task
	 * p21-i18n-walk-seam-normalize; no zh-side walk copy remains).
	 */
	private void addMaterialNames() {
		GT6EnUs.materialWalkEmittedKeys().forEach((tKey, tMaterial) ->
			addFromFamily("material", tMaterial.mNameInternal, tKey));
	}

	/**
	 * The atomic misc units — every key here mirrors a GT6EnUs literal/constant and is part of
	 * NO composed domain (the B-wave cards shrink those; see the class javadoc). The cover
	 * names are the eight atomic covers; the conveyor/robot-arm tier ladders compose from the
	 * {@link #addWireDomainUnits()} templates since p20-i18n-compose-wires.
	 */
	private void addMiscUnits() {
		addDirect("item.gt6.crowbar");
		addDirect("item.gt6.cutter");
		addDirect("item.gt6.chisel");
		addDirect("item.gt6.file"); // task p24-tool-system — the zh face rides the hand rows
		addDirect("item.gt6.saw");
		addDirect("item.gt6.builder_wand"); // task p24-builder-wand — the dump tool.name face is untranslated ASCII, the hand row composes from 建筑之杖 (itemGroup.toolHeadBuilderwand :18079 / oredict suffix :91577)
		addDirect("item.gt6.screwdriver"); // task p24-screwdriver-item — same hand-row face
		addDirect("item.gt6.hammer"); // task p25-tool-hammer-wrench — the hand row composes from 锤 (toolHeadHammer dump face 锤头 :3290, head-word first)
		addDirect("item.gt6.hammer.tooltip_prospector"); // task p30-pool-prospector — the prospector second-behavior tooltip, hand word 勘探周围的矿石 (the dump gt.lang.tool.tooltip.prospector :3514 勘探矿物 rides the mismatched-build tooltip family, the t2 ruling — not taken)
		addDirect("item.gt6.wrench"); // task p25-tool-hammer-wrench — the hand row composes from 扳手 (toolHeadWrench dump face 扳手头 :3319)
		addDirect("block.gt6.logistics_wire"); // task p32-logistics-lv2 — the dump row tmp/gregtech.lang:11847 物流线缆 (hand, the tsv direct band)
		addDirect("item.gt6.food_can_empty"); // task p25-food-can-row0 — 空食物罐头 (the dump has no cans.998 face; the 罐头 family word, MultiItemRandomTools.java:234 "Empty Food Can")
		addDirect("item.gt6.food_can_rotten_tiny"); // task p25-food-can-row0 — dump gt.multiitem.cans.11 迷你食物罐头 (腐肉)
		addDirect("item.gt6.food_can_rotten_small"); // dump :12
		addDirect("item.gt6.food_can_rotten_tall"); // dump :13
		addDirect("item.gt6.food_can_rotten_wide"); // dump :14
		addDirect("item.gt6.food_can_rotten_large"); // dump :15
		addDirect("item.gt6.food_can_rotten_huge"); // dump :16
		addDirect("item.gt6.food_can_cookies_huge"); // task p25-food-can-row0 — 超大食物罐头 (饼干) (dump cans.86 untranslated; 饼干 = the vanilla cookie face)
		addDirect("item.gt6.bending_cylinder_small"); // task p25-food-can-row0 — dump gt.metatool.01.56 小型弯曲绕筒 (Loader_Tools.java:146 "Small Bending Cylinder")
		addDirect("item.gt6.pickaxe"); // task p29-w5-t1-dig-six — 镐 (dump tagprefix tool_head_pickaxe 镐头 :895, minus 头)
		addDirect("item.gt6.pickaxe_gem"); // 镶尖镐 (dump tagprefix tool_head_pickaxe_gem 镶尖镐头 :896)
		addDirect("item.gt6.pickaxe_construction"); // 建筑镐 (dump tagprefix tool_head_construction_pickaxe 建筑镐头 :890)
		addDirect("item.gt6.shovel"); // 锹 (dump tagprefix tool_head_shovel 锹头 :914)
		addDirect("item.gt6.spade"); // 铲 (dump tagprefix tool_head_spade 铲头 :907)
		addDirect("item.gt6.universal_spade"); // 万用铲 (dump tagprefix tool_head_universal_spade 万用铲头 :910)
		// task p29-w5-t2-blade-six — 剑/小刀/斧 dump gt.lang.tool.name 行逐字；屠宰刀/木棒/双面斧 dump 无行走手翻；tooltip 四行=Loader_Tools desc 列手翻（dump tooltip 行异版不采）
		addDirect("item.gt6.sword");
		addDirect("item.gt6.knife");
		addDirect("item.gt6.butchery_knife");
		addDirect("item.gt6.club");
		addDirect("item.gt6.axe");
		addDirect("item.gt6.axe_double");
		addDirect("item.gt6.axe.tooltip");
		addDirect("item.gt6.axe_double.tooltip");
		addDirect("item.gt6.club.tooltip");
		addDirect("item.gt6.butchery_knife.tooltip");
		addDirect("item.gt6.soft_hammer"); // task p29-w5-t3-machine-face-four — dump gt.metatool.01.14 软锤 (Loader_Tools.java:125 "Soft Hammer")
		addDirect("item.gt6.monkey_wrench"); // task p29-w5-t3-machine-face-four — dump gt.metatool.01.52 活动扳手 (Loader_Tools.java:144 "Monkey Wrench")
		addDirect("item.gt6.magnifying_glass"); // task p29-w5-t3-machine-face-four — dump gt.metatool.01.62 放大镜 (Loader_Tools.java:148 "Magnifying Glass")
		addDirect("item.gt6.pincers"); // task p29-w5-t3-machine-face-four — dump gt.metatool.01.66 钳子 (Loader_Tools.java:150 "Pincers")
		addDirect("item.gt6.hoe"); // task p29-w5-t4-field-five — 锄 (dump tagprefix tool_head_hoe 锄头, minus 头)
		addDirect("item.gt6.branch_cutter"); // 修枝剪 (dump 零 branchcutter 行; hand 行, 上游 "Branch Cutter" Loader_Tools.java:133)
		addDirect("item.gt6.sense"); // 镰刀 (dump tagprefix tool_head_sense 镰刀刃, minus 刃)
		addDirect("item.gt6.plow"); // 犁 (dump tagprefix tool_head_plow 犁头, minus 头)
		addDirect("item.gt6.hand_drill"); // 手钻 (dump 零 handdrill 行; hand 行, 上游 "Hand Drill" Loader_Tools.java:152)
		addDirect("item.gt6.scissors"); // task p29-w5-t5-scene-six — 剪刀 (dump gt.metatool.01.64 :6812)
		addDirect("item.gt6.scoop"); // 捕虫网 (dump gt.metatool.01.28 :6720)
		addDirect("item.gt6.plunger"); // 搋子 (dump gt.lang.tool.name.plunger :3474)
		addDirect("item.gt6.flint_and_tinder"); // 打火石 (dump gt.metatool.01.50 :6766)
		addDirect("item.gt6.rolling_pin"); // 擀面杖 (dump gt.metatool.01.46 :6756)
		addDirect("item.gt6.bending_cylinder"); // 弯曲绕筒 (dump gt.metatool.01.54 :6786)
		// task p29-w5-t6-electric-nineteen — the 33 electric keys (19 names + 14 tooltips);
		// the upstream dump carries ZERO electric-tool display rows, so every zh face is a
		// hand word composed over the EXISTING dump roots (链锯头→链锯 / 扳手 / 圆锯
		// gt6.row.machine.buzzsaw / 螺丝刀 / 活动扳手 = the t3 metatool.01.52 word) —
		// provenance p29-w5-t6-electric-nineteen+hand33 (the TSV hand rows + the
		// gen_zhcn_ref.py HAND_TRANSLATIONS entries, the t3 double-write rule)
		addDirect("item.gt6.mining_drill_lv");
		addDirect("item.gt6.mining_drill_mv");
		addDirect("item.gt6.mining_drill_hv");
		addDirect("item.gt6.chainsaw_lv");
		addDirect("item.gt6.chainsaw_lv.tooltip");
		addDirect("item.gt6.chainsaw_mv");
		addDirect("item.gt6.chainsaw_mv.tooltip");
		addDirect("item.gt6.chainsaw_hv");
		addDirect("item.gt6.chainsaw_hv.tooltip");
		addDirect("item.gt6.wrench_lv");
		addDirect("item.gt6.wrench_lv.tooltip");
		addDirect("item.gt6.wrench_mv");
		addDirect("item.gt6.wrench_mv.tooltip");
		addDirect("item.gt6.wrench_hv");
		addDirect("item.gt6.wrench_hv.tooltip");
		addDirect("item.gt6.jackhammer_hv_normal");
		addDirect("item.gt6.jackhammer_hv_normal.tooltip");
		addDirect("item.gt6.jackhammer_hv_no_ores");
		addDirect("item.gt6.jackhammer_hv_no_ores.tooltip");
		addDirect("item.gt6.buzzsaw_lv");
		addDirect("item.gt6.buzzsaw_lv.tooltip");
		addDirect("item.gt6.screwdriver_lv");
		addDirect("item.gt6.hand_drill_lv");
		addDirect("item.gt6.hand_mixer_lv");
		addDirect("item.gt6.hand_mixer_lv.tooltip");
		addDirect("item.gt6.monkey_wrench_lv");
		addDirect("item.gt6.monkey_wrench_lv.tooltip");
		addDirect("item.gt6.monkey_wrench_mv");
		addDirect("item.gt6.monkey_wrench_mv.tooltip");
		addDirect("item.gt6.monkey_wrench_hv");
		addDirect("item.gt6.monkey_wrench_hv.tooltip");
		addDirect("item.gt6.trimmer_lv");
		addDirect("item.gt6.mode_switch.tooltip");
		addDirect("item.gt6.shape_extruder_plate"); // task p26-w1-press-extruder-molds — dump gt.multiitem.technological.10001 模具 (板) (:10129)
		addDirect("item.gt6.shape_extruder_rod"); // task p26-w1-press-extruder-molds — dump gt.multiitem.technological.10027 模具 (杆) (:10185)
		addDirect("item.gt6.cover_redstone_emitter");
		addDirect("item.gt6.cover_redstone_conductor_in");
		addDirect("item.gt6.cover_redstone_conductor_out");
		addDirect("item.gt6.cover_redstone_machine_switch");
		addDirect("item.gt6.cover_shutter");
		addDirect("item.gt6.cover_item_filter");
		addDirect("item.gt6.cover_item_retriever");
		// task p33-logistics-covers-12 — the 12 logistics covers (zh_cn_ref.tsv 回写行:
		// 上游 tmp/gregtech.lang 1086-1099 显示名)
		addDirect("item.gt6.cover_logistics_display_cpu_logic");
		addDirect("item.gt6.cover_logistics_display_cpu_control");
		addDirect("item.gt6.cover_logistics_display_cpu_storage");
		addDirect("item.gt6.cover_logistics_display_cpu_conversion");
		addDirect("item.gt6.cover_logistics_fluid_export");
		addDirect("item.gt6.cover_logistics_fluid_import");
		addDirect("item.gt6.cover_logistics_fluid_storage");
		addDirect("item.gt6.cover_logistics_item_export");
		addDirect("item.gt6.cover_logistics_item_import");
		addDirect("item.gt6.cover_logistics_item_storage");
		addDirect("item.gt6.cover_logistics_generic_export");
		addDirect("item.gt6.cover_logistics_generic_import");
		addDirect("item.gt6.cover_logistics_generic_storage");
		addDirect("item.gt6.cover_logistics_generic_dump");
		addDirect("item.gt6.cover_auto_redstone_machine_switch");
		addDirect("item.gt6.cover_controller");
		// task p34-covers-gameplay-10 — the 10 gameplay covers (zh faces: the dump
		// gt.multiitem.technological 1007/1008/1020/1022/1024/1027/2000 name column
		// verbatim + the hand torch/repeater/template rows)
		addDirect("item.gt6.cover_vent");
		addDirect("item.gt6.cover_drain");
		addDirect("item.gt6.cover_pressure_valve");
		addDirect("item.gt6.cover_fluid_filter");
		addDirect("item.gt6.cover_redstone_torch");
		addDirect("item.gt6.cover_redstone_repeater");
		addDirect("item.gt6.cover_selector_redstone");
		addDirect("item.gt6.cover_selector_manual");
		addDirect("item.gt6.cover_selector_button_panel");
		addDirect("item.gt6.integrated_circuit");
		addDirect(GT6Circuits.TOOLTIP_KEY);
		// task p29-w4-hot-lube ④ — the Lubricant Bucket + the "Industrial Use ONLY!"
		// tooltip (仅限工业用途！, the :617 hand row; 润滑油桶 the naming candidate).
		addDirect("item.gt6.lubricant_bucket");
		addDirect(gregtech6.item.GT6LubricantBucket.TOOLTIP_KEY);
		addDirect(GT6JeiPlugin.INFO_KEY_COKE_OVEN);
		addDirect("block.gt6.example_chest");
		// task p28-cfoam-lang-key: the TestMachine framework blocks joined the coverage gate —
		// no getName override, so their Jade line resolves the vanilla keys; faces follow the
		// TestMachineBlock javadoc's ticking/passive vocabulary (en "Test Machine (Passive)")
		addDirect("block.gt6.test_machine");
		addDirect("block.gt6.test_machine_idle");
		addDirect("fluid.gt6.iron_molten");
		addDirect("fluid.gt6.natural_gas");
	}

	/** Family join: derive nothing here beyond the caller's key — look the dump suffix up, skip absent/review rows. */
	private void addFromFamily(String aKind, String aSource, String aKey) {
		RefRow tRow = reference.get(aKind) == null ? null : reference.get(aKind).get(aSource);
		if (tRow != null && !tRow.skipped()) add(aKey, tRow.value());
	}

	/** Hand-row join: the key IS the final gt6 lang key (status=hand direct rows); skip absent/review rows. */
	private void addDirect(String aKey) {
		RefRow tRow = reference.get("direct") == null ? null : reference.get("direct").get(aKey);
		if (tRow != null && !tRow.skipped()) add(aKey, tRow.value());
	}

	/** The placeables band (task p32-placeables) — the deco TE names over the tsv direct rows. */
	private void addPlaceablesUnits() {
		addDirect("block.gt6.greg_o_lantern");
		addDirect("block.gt6.sandwich");
		addDirect("block.gt6.placed_rock");
		addDirect("block.gt6.placed_stick");
		addDirect("block.gt6.placed_ingot");
		addDirect("block.gt6.placed_plate");
		addDirect("block.gt6.placed_gem_plate");
		addDirect("block.gt6.placed_scrap");
	}

	/**
	 * Parses {@link #REFERENCE_RESOURCE}: {@code #}-comment and blank lines skipped, data rows
	 * are {@code kind<TAB>source<TAB>value<TAB>status}. Package-private static so the parity
	 * test reuses the single parse implementation (it asserts no hand row is orphaned).
	 */
    private void addBatteryFamily() {
		addDirect("item.gt6.battery_lead_acid_ulv");
		addDirect("item.gt6.battery_lead_acid_lv");
		addDirect("item.gt6.battery_lead_acid_mv");
		addDirect("item.gt6.battery_lead_acid_hv");
		addDirect("item.gt6.battery_lead_acid_ev");
		addDirect("item.gt6.battery_alkaline_ulv");
		addDirect("item.gt6.battery_alkaline_lv");
		addDirect("item.gt6.battery_alkaline_mv");
		addDirect("item.gt6.battery_alkaline_hv");
		addDirect("item.gt6.battery_alkaline_ev");
		addDirect("item.gt6.battery_nicd_ulv");
		addDirect("item.gt6.battery_nicd_lv");
		addDirect("item.gt6.battery_nicd_mv");
		addDirect("item.gt6.battery_nicd_hv");
		addDirect("item.gt6.battery_nicd_ev");
		addDirect("item.gt6.battery_licoo2_ulv");
		addDirect("item.gt6.battery_licoo2_lv");
		addDirect("item.gt6.battery_licoo2_mv");
		addDirect("item.gt6.battery_licoo2_hv");
		addDirect("item.gt6.battery_licoo2_ev");
		addDirect("item.gt6.battery_limn_ulv");
		addDirect("item.gt6.battery_limn_lv");
		addDirect("item.gt6.battery_limn_mv");
		addDirect("item.gt6.battery_limn_hv");
		addDirect("item.gt6.battery_limn_ev");
		addDirect("item.gt6.energium_red_ulv");
		addDirect("item.gt6.energium_red_lv");
		addDirect("item.gt6.energium_red_mv");
		addDirect("item.gt6.energium_red_hv");
		addDirect("item.gt6.energium_red_ev");
		addDirect("item.gt6.energium_red_iv");
		addDirect("item.gt6.energium_cyan_ulv");
		addDirect("item.gt6.energium_cyan_lv");
		addDirect("item.gt6.energium_cyan_mv");
		addDirect("item.gt6.energium_cyan_hv");
		addDirect("item.gt6.energium_cyan_ev");
		addDirect("item.gt6.energium_cyan_iv");
		addDirect("item.gt6.battery_cell_lead_acid");
		addDirect("item.gt6.battery_cell_alkaline");
		addDirect("item.gt6.battery_cell_nicd");
		addDirect("item.gt6.battery_cell_licoo2");
		addDirect("item.gt6.battery_cell_limn");
		addDirect("item.gt6.circuit_primitive");
		addDirect("item.gt6.circuit_basic");
		addDirect("item.gt6.circuit_good");
		addDirect("item.gt6.circuit_advanced");
		addDirect("item.gt6.circuit_elite");
		addDirect("item.gt6.circuit_master");
		addDirect("item.gt6.circuit_ultimate");
		addDirect("block.gt6.battery_box_ulv");
		addDirect("block.gt6.battery_box_lv");
		addDirect("block.gt6.battery_box_mv");
		addDirect("block.gt6.battery_box_hv");
		addDirect("block.gt6.battery_box_ev");
		addDirect("block.gt6.battery_box_iv");
		addDirect("block.gt6.battery_box_large_ulv");
		addDirect("block.gt6.battery_box_large_lv");
		addDirect("block.gt6.battery_box_large_mv");
		addDirect("block.gt6.battery_box_large_hv");
		addDirect("block.gt6.battery_box_large_ev");
		addDirect("block.gt6.battery_box_large_iv");
		// task p32-magic-absorber — the Magic Field Absorber (the dump :10891 face verbatim, tail-append)
		addDirect("block.gt6.magic_absorber");
    }

	static Map<String, Map<String, RefRow>> loadReference() {
		Map<String, Map<String, RefRow>> rTable = new HashMap<>();
		InputStream tStream = GT6ZhCn.class.getResourceAsStream(REFERENCE_RESOURCE);
		if (tStream == null) throw new IllegalStateException("reference table missing on the classpath: " + REFERENCE_RESOURCE);
		try (BufferedReader tReader = new BufferedReader(new InputStreamReader(tStream, StandardCharsets.UTF_8))) {
			String tLine;
			while ((tLine = tReader.readLine()) != null) {
				if (tLine.isEmpty() || tLine.charAt(0) == '#') continue;
				String[] tFields = tLine.split("\t", -1);
				if (tFields.length != 4) throw new IllegalStateException("malformed reference row: " + tLine);
				rTable.computeIfAbsent(tFields[0], k -> new HashMap<>()).put(tFields[1], new RefRow(tFields[2], tFields[3]));
			}
		} catch (IOException aE) {
			throw new IllegalStateException("failed to read " + REFERENCE_RESOURCE, aE);
		}
		return rTable;
	}
}
