package gregtech6.datagen;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import gregapi.oredict.MaterialRegistry;
import gregapi.oredict.OreDictMaterial;
import gregapi.oredict.OreDictPrefix;
import gregtech6.item.GT6Circuits;
import gregtech6.item.MaterialPrefixItem;
import gregtech6.jei.GT6JeiPlugin;
import gregtech6.registry.GT6Tools;
import gregtech6.registry.GTMaterialBlocks;
import gregtech6.registry.GTMaterialItems;
import gregtech6.registry.GTWires;
import net.minecraft.data.PackOutput;
import net.minecraftforge.common.data.LanguageProvider;

/**
 * zh_cn lang, the A-wave small-unit companion of {@link GT6EnUs} (task p20-i18n-zhcn-provider,
 * ADR 2026-09-06-p20-i18n-zhcn-pipeline): zh_cn.json is GENERATED by this provider — the
 * hand-written-JSON red line forbids editing it directly. The translation VALUES come from the
 * committed reference table {@code /gregtech6/lang/zh_cn_ref.tsv} (produced by
 * {@code mdk/tools/gen_zhcn_ref.py} from the GT6 1.7.10 zh lang dump + a hand-translation
 * layer); the lang KEYS are derived here with the same single
 * {@link MaterialPrefixItem#snakeCase} implementation the en provider uses, so no second
 * snake_case algorithm exists (the Python side of the pipeline deliberately carries zero key
 * logic, ADR §1.1).
 *
 * <p>Four small-unit walks, each mirroring the exact {@link GT6EnUs} walk over the same
 * registry sources (per-key English fallback for skipped rows is vanilla's built-in
 * bilingual chain — LanguageManager.java:50-52 + ClientLanguage.java:29-46 — so zero
 * fallback code lives here):
 * <ol>
 * <li>{@link #addTabTitles()} — the creative tab titles: item prefix tabs
 *     ({@code itemGroup.gt6.<snake>} over {@link GTMaterialItems#tabPrefixes()}), block prefix
 *     tabs (over {@link GTMaterialBlocks#tabPrefixes()}) and the special MTE-category tabs,
 *     joined against the dump's {@code itemGroup.<camel>} family or the hand rows;</li>
 * <li>{@link #addPrefixTemplates()} — the {@code gt6.tagprefix.<snake>} display templates.
 *     The en provider emits all 467 OP prefixes; zh emits ONLY the hand-translated in-use set
 *     (status=hand direct rows, ADR §1.2 — the dump has no authoritative template face, and
 *     affix stripping would be statistical generalisation multiplied by 1273 materials). The
 *     parity test (GT6LangParityTest) structurally guarantees zh ⊆ en;</li>
 * <li>{@link #addMaterialNames()} — the {@code gt6.material.<snake>} small units, the exact
 *     {@link GT6EnUs#addMaterialNames()} walk (alias merge, first mID wins) joined against the
 *     dump's {@code gt.material.<Pascal>} family;</li>
 * <li>{@link #addMiscUnits()} — the atomic misc keys (tools, the eight atomic covers, the
 *     circuit selector tag + its configuration tooltip, the JEI coke-oven info page, the
 *     example chest, the two port fluids). The COMPOSED domains (wire/cable families, stone
 *     variants, kinetics/boiler/burning-box rows, machine tiers, attachments, conveyor/robot
 *     arm covers) are intentionally absent — they become B-wave template keys
 *     (p20-i18n-compose-wires/-rows) and are pinned absent by the parity test's negative
 *     assertions in the meantime.</li>
 * </ol>
 *
 * <p>Rows with status {@code review} (pure-ASCII dump values, suspected untranslated, e.g.
 * {@code gt.material.Magnite=Magnite}, tmp/gregtech.lang:5003) and rows with no reference
 * entry at all are skipped: the runtime falls back to English per key. The {@code mte} family
 * in the TSV is deliberately unused here — it is inert census data until the MTE ID-join
 * subface lands (arch card tasks.p20-arch-i18n).
 *
 * <p>Non-final on purpose: GT6LangParityTest records {@code add()} through a same-package
 * subclass (the GT6EnUsJeiInfoTest:52-64 posture) to collect both providers' key sets in a
 * bare JVM without a datagen run.
 */
public class GT6ZhCn extends LanguageProvider {

	/** Classpath location of the generated reference table (rides the jar, ADR §1.1). */
	static final String REFERENCE_RESOURCE = "/gregtech6/lang/zh_cn_ref.tsv";

	/** One reference row: the translation value and its pipeline status. */
	record RefRow(String value, String status) {
		/** review rows are suspected-untranslated dump entries — the provider skips them. */
		boolean skipped() {
			return "review".equals(status);
		}
	}

	private final Map<String, Map<String, RefRow>> reference;

	public GT6ZhCn(PackOutput output) {
		super(output, GT6DataGenerators.MOD_ID, "zh_cn");
		this.reference = loadReference();
	}

	@Override
	protected void addTranslations() {
		addTabTitles();
		addPrefixTemplates();
		addMaterialNames();
		addMiscUnits();
	}

	/** The item + block prefix tab titles and the special MTE-category tabs (mirror of GT6EnUs.addTabTitles/addBlockTabTitles + the tab literals). */
	private void addTabTitles() {
		for (OreDictPrefix tPrefix : GTMaterialItems.tabPrefixes()) {
			addFromFamily("itemgroup", tPrefix.mNameInternal,
				"itemGroup.gt6." + MaterialPrefixItem.snakeCase(tPrefix.mNameInternal));
		}
		for (OreDictPrefix tPrefix : GTMaterialBlocks.tabPrefixes()) {
			addFromFamily("itemgroup", tPrefix.mNameInternal,
				"itemGroup.gt6." + MaterialPrefixItem.snakeCase(tPrefix.mNameInternal));
		}
		// the special tabs have no dump face (the 1.7.10 dump's itemGroup family holds prefix
		// tabs only) — their titles ride the hand rows, keyed by the same literals/constants
		// the en walk uses so the faces cannot drift
		addDirect("itemGroup.gt6.chests");
		addDirect("itemGroup.gt6.machines");
		addDirect("itemGroup.gt6.multiblocks");
		addDirect("itemGroup.gt6.fluid_containers");
		addDirect("itemGroup.gt6.fluid_pipes");
		addDirect("itemGroup.gt6.electric_wires");
		addDirect(GTWires.REDSTONE_TAB_TITLE_KEY);
		addDirect(GTWires.LASER_TAB_TITLE_KEY);
		addDirect(GT6Tools.TAB_TITLE_KEY);
	}

	/** Only the hand-translated in-use prefix templates (mirror of GT6EnUs.addPrefixTemplates over OP.VALUES). */
	private void addPrefixTemplates() {
		Set<String> tSeen = new HashSet<>();
		for (OreDictPrefix tPrefix : OreDictPrefix.VALUES) {
			String tKey = "gt6.tagprefix." + MaterialPrefixItem.snakeCase(tPrefix.mNameInternal);
			if (!tSeen.add(tKey)) continue; // same snake_case-collision guard as the en walk
			addDirect(tKey);
		}
	}

	/** The material small units, the exact GT6EnUs.addMaterialNames walk (alias merge, first mID wins). */
	private void addMaterialNames() {
		Set<String> tSeen = new HashSet<>();
		for (OreDictMaterial tMaterial : MaterialRegistry.INSTANCE.MATERIAL_ARRAY) {
			if (tMaterial == null || tMaterial.mID < 0) continue;
			tMaterial = MaterialRegistry.INSTANCE.get(tMaterial); // alias merge, MaterialRegistry.java:182-185
			if (tMaterial == null || tMaterial.mID < 0 || tMaterial.mNameLocal == null) continue;
			String tKey = "gt6.material." + MaterialPrefixItem.snakeCase(tMaterial.mNameInternal);
			if (!tSeen.add(tKey)) continue; // first (lowest mID) definition wins
			addFromFamily("material", tMaterial.mNameInternal, tKey);
		}
	}

	/**
	 * The atomic misc units — every key here mirrors a GT6EnUs literal/constant and is part of
	 * NO composed domain (the B-wave cards shrink those; see the class javadoc). The cover
	 * names are the eight atomic covers; the conveyor/robot-arm tier ladders stay absent
	 * (p20-i18n-compose-wires).
	 */
	private void addMiscUnits() {
		addDirect("item.gt6.crowbar");
		addDirect("item.gt6.cutter");
		addDirect("item.gt6.chisel");
		addDirect("item.gt6.cover_redstone_emitter");
		addDirect("item.gt6.cover_redstone_conductor_in");
		addDirect("item.gt6.cover_redstone_conductor_out");
		addDirect("item.gt6.cover_redstone_machine_switch");
		addDirect("item.gt6.cover_shutter");
		addDirect("item.gt6.cover_item_filter");
		addDirect("item.gt6.cover_auto_redstone_machine_switch");
		addDirect("item.gt6.cover_controller");
		addDirect("item.gt6.integrated_circuit");
		addDirect(GT6Circuits.TOOLTIP_KEY);
		addDirect(GT6JeiPlugin.INFO_KEY_COKE_OVEN);
		addDirect("block.gt6.example_chest");
		addDirect("fluid.gt6.iron_molten");
		addDirect("fluid.gt6.natural_gas");
	}

	/** Family join: derive nothing here beyond the caller's key — look the dump suffix up, skip absent/review rows. */
	private void addFromFamily(String aKind, String aSource, String aKey) {
		RefRow tRow = reference.get(aKind) == null ? null : reference.get(aKind).get(aSource);
		if (tRow != null && !tRow.skipped()) add(aKey, tRow.value());
	}

	/** Hand-row join: the key IS the final gt6 lang key (status=hand direct rows); skip absent/review rows. */
	private void addDirect(String aKey) {
		RefRow tRow = reference.get("direct") == null ? null : reference.get("direct").get(aKey);
		if (tRow != null && !tRow.skipped()) add(aKey, tRow.value());
	}

	/**
	 * Parses {@link #REFERENCE_RESOURCE}: {@code #}-comment and blank lines skipped, data rows
	 * are {@code kind<TAB>source<TAB>value<TAB>status}. Package-private static so the parity
	 * test reuses the single parse implementation (it asserts no hand row is orphaned).
	 */
	static Map<String, Map<String, RefRow>> loadReference() {
		Map<String, Map<String, RefRow>> rTable = new HashMap<>();
		InputStream tStream = GT6ZhCn.class.getResourceAsStream(REFERENCE_RESOURCE);
		if (tStream == null) throw new IllegalStateException("reference table missing on the classpath: " + REFERENCE_RESOURCE);
		try (BufferedReader tReader = new BufferedReader(new InputStreamReader(tStream, StandardCharsets.UTF_8))) {
			String tLine;
			while ((tLine = tReader.readLine()) != null) {
				if (tLine.isEmpty() || tLine.charAt(0) == '#') continue;
				String[] tFields = tLine.split("\t", -1);
				if (tFields.length != 4) throw new IllegalStateException("malformed reference row: " + tLine);
				rTable.computeIfAbsent(tFields[0], k -> new HashMap<>()).put(tFields[1], new RefRow(tFields[2], tFields[3]));
			}
		} catch (IOException aE) {
			throw new IllegalStateException("failed to read " + REFERENCE_RESOURCE, aE);
		}
		return rTable;
	}
}
