#!/usr/bin/env python3
"""food-fluids-b2 — the drink-seam live chain (the foodb1 shape).

  A the DRINK arms: one real right-click dispatch per arm (/gt6drink use drives
    ServerPlayerGameMode.useItemOn with an EMPTY main hand at the metal barrel —
    the GTBarrelBlock.use seam, not a re-implementation):
    - vodka at food 15: CONSUME, 250 mB drained, food 15 -> 17 (the food row),
    - potion.health at a FULL bar: CONSUME, then PASS on the now-empty barrel (the
      zero-food row bypasses the hunger gate — the canEat(food==0) fold),
    - minecraft:water: CONSUME (the vanilla-carried "water" map row),
    - gt6:short_mead at food 10: CONSUME, food 10 -> 13 (the KEPT census face),
    - gt6:chlorine: PASS, tank untouched (the unregistered-fluid negative).

  C the census arms: one 144 mB fill/draw round-trip per row, FOOD_B2_SPECS order —
    all 103 registrations resolve through the LIVE tank handler, with the four
    temperature representatives pinned at 250 mB stat (fireresistance 375 K /
    riverwater 273 K / rottendrink 275 K / tainted 300 K).

passes=2 is the idempotency proof (the [0,0] of this chain).

Run:  GT6_SESSION=off python3 tools/rcon/chains/food_drink.py
"""

import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
for _path in (str(_HERE), str(_HERE.parent)):
    if _path not in sys.path:
        sys.path.insert(0, _path)

import gt6world
from framework import Chain, Step, main, phase

F = gt6world.fmt

# the single-block barrel site x=404 z=20 — the z=20 row is crowded (foodb1's
# band bbox ends at x=401, the act chest bbox starts at x=408), and this one
# block keeps the bbox at 402..406, disjoint from both; the wiremill band at x=404
# sits z=172, far south of this row
BARREL_SITE = gt6world.Site(404, 64, 20)
BARREL = F(BARREL_SITE)  # 404 64 20

TEMP_PINS = {'potion.fireresistance': 375, 'riverwater': 273, 'rottendrink': 275, 'potion.tainted': 300}

B2_IDS = [
	"potion.tainted",
	"potion.awkward",
	"potion.thick",
	"potion.mundane",
	"potion.damage",
	"potion.damage.strong",
	"potion.damage.splash",
	"potion.damage.strong.splash",
	"potion.health",
	"potion.health.strong",
	"potion.health.splash",
	"potion.health.strong.splash",
	"potion.jump",
	"potion.jump.strong",
	"potion.jump.splash",
	"potion.jump.strong.splash",
	"potion.speed",
	"potion.speed.strong",
	"potion.speed.long",
	"potion.speed.splash",
	"potion.speed.strong.splash",
	"potion.speed.long.splash",
	"potion.strength",
	"potion.strength.strong",
	"potion.strength.long",
	"potion.strength.splash",
	"potion.strength.strong.splash",
	"potion.strength.long.splash",
	"potion.regen",
	"potion.regen.strong",
	"potion.regen.long",
	"potion.regen.splash",
	"potion.regen.strong.splash",
	"potion.regen.long.splash",
	"potion.poison",
	"potion.poison.strong",
	"potion.poison.long",
	"potion.poison.splash",
	"potion.poison.strong.splash",
	"potion.poison.long.splash",
	"potion.fireresistance",
	"potion.fireresistance.long",
	"potion.fireresistance.splash",
	"potion.fireresistance.long.splash",
	"potion.nightvision",
	"potion.nightvision.long",
	"potion.nightvision.splash",
	"potion.nightvision.long.splash",
	"potion.weakness",
	"potion.weakness.long",
	"potion.weakness.splash",
	"potion.weakness.long.splash",
	"potion.slowness",
	"potion.slowness.long",
	"potion.slowness.splash",
	"potion.slowness.long.splash",
	"potion.waterbreathing",
	"potion.waterbreathing.long",
	"potion.waterbreathing.splash",
	"potion.waterbreathing.long.splash",
	"potion.invisibility",
	"potion.invisibility.long",
	"potion.invisibility.splash",
	"potion.invisibility.long.splash",
	"potion.damage.lingering",
	"potion.damage.strong.lingering",
	"potion.health.lingering",
	"potion.health.strong.lingering",
	"potion.jump.lingering",
	"potion.jump.strong.lingering",
	"potion.speed.lingering",
	"potion.speed.strong.lingering",
	"potion.speed.long.lingering",
	"potion.strength.lingering",
	"potion.strength.strong.lingering",
	"potion.strength.long.lingering",
	"potion.regen.lingering",
	"potion.regen.strong.lingering",
	"potion.regen.long.lingering",
	"potion.poison.lingering",
	"potion.poison.strong.lingering",
	"potion.poison.long.lingering",
	"potion.fireresistance.lingering",
	"potion.fireresistance.long.lingering",
	"potion.nightvision.lingering",
	"potion.nightvision.long.lingering",
	"potion.weakness.lingering",
	"potion.weakness.long.lingering",
	"potion.slowness.lingering",
	"potion.slowness.long.lingering",
	"potion.waterbreathing.lingering",
	"potion.waterbreathing.long.lingering",
	"potion.invisibility.lingering",
	"potion.invisibility.long.lingering",
	"riverwater",
	"ic2distilledwater",
	"goldencarrotjuice",
	"holywater",
	"rottendrink",
	"poison",
	"chocolatemilk",
	"medicine.heal",
	"medicine.laxative",
]

steps = [
	Step(f"setblock {BARREL} gt6:barrel_metal", expect="Changed the block"),
]

phase("A: the drink arms — one real useItemOn dispatch per arm (the GTBarrelBlock.use seam)")
steps += [
	Step("gt6drink clear", expect="food=20 effects=0"),
	Step("gt6drink hunger 15", expect="food level set: food=15"),
	Step(f"gt6tank fill {BARREL} gt6:vodka 250",
	     expect="filled 250/250 L of gt6:vodka (ACCEPTED)"),
	Step(f"gt6drink use {BARREL}",
	     expect="result=CONSUME tank=empty food=17"),
	Step("gt6drink clear", expect="food=20 effects=0"),
	Step(f"gt6tank fill {BARREL} gt6:potion.health 250",
	     expect="filled 250/250 L of gt6:potion.health (ACCEPTED)"),
	Step(f"gt6drink use {BARREL}",
	     expect="result=CONSUME tank=empty food=20"),
	Step(f"gt6drink use {BARREL}",
	     expect="result=PASS tank=empty food=20"),
	Step("gt6drink clear", expect="food=20 effects=0"),
	Step(f"gt6tank fill {BARREL} minecraft:water 250",
	     expect="filled 250/250 L of minecraft:water (ACCEPTED)"),
	Step(f"gt6drink use {BARREL}",
	     expect="result=CONSUME tank=empty food=20"),
	Step("gt6drink hunger 10", expect="food level set: food=10"),
	Step(f"gt6tank fill {BARREL} gt6:short_mead 250",
	     expect="filled 250/250 L of gt6:short_mead (ACCEPTED)"),
	Step(f"gt6drink use {BARREL}",
	     expect="result=CONSUME tank=empty food=13"),
	Step("gt6drink clear", expect="food=20 effects=0"),
	Step(f"gt6tank fill {BARREL} gt6:chlorine 250",
	     expect="filled 250/250 L of gt6:chlorine (ACCEPTED)"),
	Step(f"gt6drink use {BARREL}",
	     expect="result=PASS tank=gt6:chlorine 250L food=20"),
	# the negative arm leaves its 250 L in the barrel — the single-fluid rule
	# (FluidTankGT fill contains-gate) would reject the census's first fill, so
	# the band empties before phase C
	Step(f"gt6tank draw {BARREL} 250",
	     expect="drawn 250/250 L of gt6:chlorine (ACCEPTED)"),
]

phase("C: the census arms — 144 mB fill/draw round-trip per row (the full 103-registration live walk)")
steps += [
	Step(f"gt6tank fill {BARREL} gt6:potion.tainted 250",
	     expect="filled 250/250 L of gt6:potion.tainted (ACCEPTED)"),
	Step(f"gt6tank stat {BARREL}",
	     expect="250/64000 L of gt6:potion.tainted, temperature 300 K"),
	Step(f"gt6tank draw {BARREL} 250",
	     expect="drawn 250/250 L of gt6:potion.tainted (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.awkward 144",
	     expect="filled 144/144 L of gt6:potion.awkward (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.awkward (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.thick 144",
	     expect="filled 144/144 L of gt6:potion.thick (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.thick (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.mundane 144",
	     expect="filled 144/144 L of gt6:potion.mundane (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.mundane (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.damage 144",
	     expect="filled 144/144 L of gt6:potion.damage (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.damage (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.damage.strong 144",
	     expect="filled 144/144 L of gt6:potion.damage.strong (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.damage.strong (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.damage.splash 144",
	     expect="filled 144/144 L of gt6:potion.damage.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.damage.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.damage.strong.splash 144",
	     expect="filled 144/144 L of gt6:potion.damage.strong.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.damage.strong.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.health 144",
	     expect="filled 144/144 L of gt6:potion.health (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.health (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.health.strong 144",
	     expect="filled 144/144 L of gt6:potion.health.strong (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.health.strong (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.health.splash 144",
	     expect="filled 144/144 L of gt6:potion.health.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.health.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.health.strong.splash 144",
	     expect="filled 144/144 L of gt6:potion.health.strong.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.health.strong.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.jump 144",
	     expect="filled 144/144 L of gt6:potion.jump (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.jump (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.jump.strong 144",
	     expect="filled 144/144 L of gt6:potion.jump.strong (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.jump.strong (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.jump.splash 144",
	     expect="filled 144/144 L of gt6:potion.jump.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.jump.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.jump.strong.splash 144",
	     expect="filled 144/144 L of gt6:potion.jump.strong.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.jump.strong.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.speed 144",
	     expect="filled 144/144 L of gt6:potion.speed (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.speed (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.speed.strong 144",
	     expect="filled 144/144 L of gt6:potion.speed.strong (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.speed.strong (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.speed.long 144",
	     expect="filled 144/144 L of gt6:potion.speed.long (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.speed.long (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.speed.splash 144",
	     expect="filled 144/144 L of gt6:potion.speed.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.speed.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.speed.strong.splash 144",
	     expect="filled 144/144 L of gt6:potion.speed.strong.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.speed.strong.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.speed.long.splash 144",
	     expect="filled 144/144 L of gt6:potion.speed.long.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.speed.long.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.strength 144",
	     expect="filled 144/144 L of gt6:potion.strength (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.strength (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.strength.strong 144",
	     expect="filled 144/144 L of gt6:potion.strength.strong (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.strength.strong (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.strength.long 144",
	     expect="filled 144/144 L of gt6:potion.strength.long (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.strength.long (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.strength.splash 144",
	     expect="filled 144/144 L of gt6:potion.strength.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.strength.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.strength.strong.splash 144",
	     expect="filled 144/144 L of gt6:potion.strength.strong.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.strength.strong.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.strength.long.splash 144",
	     expect="filled 144/144 L of gt6:potion.strength.long.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.strength.long.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.regen 144",
	     expect="filled 144/144 L of gt6:potion.regen (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.regen (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.regen.strong 144",
	     expect="filled 144/144 L of gt6:potion.regen.strong (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.regen.strong (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.regen.long 144",
	     expect="filled 144/144 L of gt6:potion.regen.long (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.regen.long (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.regen.splash 144",
	     expect="filled 144/144 L of gt6:potion.regen.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.regen.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.regen.strong.splash 144",
	     expect="filled 144/144 L of gt6:potion.regen.strong.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.regen.strong.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.regen.long.splash 144",
	     expect="filled 144/144 L of gt6:potion.regen.long.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.regen.long.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.poison 144",
	     expect="filled 144/144 L of gt6:potion.poison (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.poison (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.poison.strong 144",
	     expect="filled 144/144 L of gt6:potion.poison.strong (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.poison.strong (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.poison.long 144",
	     expect="filled 144/144 L of gt6:potion.poison.long (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.poison.long (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.poison.splash 144",
	     expect="filled 144/144 L of gt6:potion.poison.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.poison.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.poison.strong.splash 144",
	     expect="filled 144/144 L of gt6:potion.poison.strong.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.poison.strong.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.poison.long.splash 144",
	     expect="filled 144/144 L of gt6:potion.poison.long.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.poison.long.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.fireresistance 250",
	     expect="filled 250/250 L of gt6:potion.fireresistance (ACCEPTED)"),
	Step(f"gt6tank stat {BARREL}",
	     expect="250/64000 L of gt6:potion.fireresistance, temperature 375 K"),
	Step(f"gt6tank draw {BARREL} 250",
	     expect="drawn 250/250 L of gt6:potion.fireresistance (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.fireresistance.long 144",
	     expect="filled 144/144 L of gt6:potion.fireresistance.long (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.fireresistance.long (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.fireresistance.splash 144",
	     expect="filled 144/144 L of gt6:potion.fireresistance.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.fireresistance.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.fireresistance.long.splash 144",
	     expect="filled 144/144 L of gt6:potion.fireresistance.long.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.fireresistance.long.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.nightvision 144",
	     expect="filled 144/144 L of gt6:potion.nightvision (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.nightvision (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.nightvision.long 144",
	     expect="filled 144/144 L of gt6:potion.nightvision.long (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.nightvision.long (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.nightvision.splash 144",
	     expect="filled 144/144 L of gt6:potion.nightvision.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.nightvision.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.nightvision.long.splash 144",
	     expect="filled 144/144 L of gt6:potion.nightvision.long.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.nightvision.long.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.weakness 144",
	     expect="filled 144/144 L of gt6:potion.weakness (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.weakness (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.weakness.long 144",
	     expect="filled 144/144 L of gt6:potion.weakness.long (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.weakness.long (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.weakness.splash 144",
	     expect="filled 144/144 L of gt6:potion.weakness.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.weakness.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.weakness.long.splash 144",
	     expect="filled 144/144 L of gt6:potion.weakness.long.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.weakness.long.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.slowness 144",
	     expect="filled 144/144 L of gt6:potion.slowness (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.slowness (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.slowness.long 144",
	     expect="filled 144/144 L of gt6:potion.slowness.long (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.slowness.long (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.slowness.splash 144",
	     expect="filled 144/144 L of gt6:potion.slowness.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.slowness.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.slowness.long.splash 144",
	     expect="filled 144/144 L of gt6:potion.slowness.long.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.slowness.long.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.waterbreathing 144",
	     expect="filled 144/144 L of gt6:potion.waterbreathing (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.waterbreathing (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.waterbreathing.long 144",
	     expect="filled 144/144 L of gt6:potion.waterbreathing.long (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.waterbreathing.long (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.waterbreathing.splash 144",
	     expect="filled 144/144 L of gt6:potion.waterbreathing.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.waterbreathing.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.waterbreathing.long.splash 144",
	     expect="filled 144/144 L of gt6:potion.waterbreathing.long.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.waterbreathing.long.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.invisibility 144",
	     expect="filled 144/144 L of gt6:potion.invisibility (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.invisibility (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.invisibility.long 144",
	     expect="filled 144/144 L of gt6:potion.invisibility.long (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.invisibility.long (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.invisibility.splash 144",
	     expect="filled 144/144 L of gt6:potion.invisibility.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.invisibility.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.invisibility.long.splash 144",
	     expect="filled 144/144 L of gt6:potion.invisibility.long.splash (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.invisibility.long.splash (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.damage.lingering 144",
	     expect="filled 144/144 L of gt6:potion.damage.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.damage.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.damage.strong.lingering 144",
	     expect="filled 144/144 L of gt6:potion.damage.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.damage.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.health.lingering 144",
	     expect="filled 144/144 L of gt6:potion.health.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.health.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.health.strong.lingering 144",
	     expect="filled 144/144 L of gt6:potion.health.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.health.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.jump.lingering 144",
	     expect="filled 144/144 L of gt6:potion.jump.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.jump.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.jump.strong.lingering 144",
	     expect="filled 144/144 L of gt6:potion.jump.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.jump.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.speed.lingering 144",
	     expect="filled 144/144 L of gt6:potion.speed.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.speed.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.speed.strong.lingering 144",
	     expect="filled 144/144 L of gt6:potion.speed.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.speed.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.speed.long.lingering 144",
	     expect="filled 144/144 L of gt6:potion.speed.long.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.speed.long.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.strength.lingering 144",
	     expect="filled 144/144 L of gt6:potion.strength.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.strength.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.strength.strong.lingering 144",
	     expect="filled 144/144 L of gt6:potion.strength.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.strength.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.strength.long.lingering 144",
	     expect="filled 144/144 L of gt6:potion.strength.long.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.strength.long.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.regen.lingering 144",
	     expect="filled 144/144 L of gt6:potion.regen.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.regen.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.regen.strong.lingering 144",
	     expect="filled 144/144 L of gt6:potion.regen.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.regen.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.regen.long.lingering 144",
	     expect="filled 144/144 L of gt6:potion.regen.long.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.regen.long.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.poison.lingering 144",
	     expect="filled 144/144 L of gt6:potion.poison.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.poison.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.poison.strong.lingering 144",
	     expect="filled 144/144 L of gt6:potion.poison.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.poison.strong.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.poison.long.lingering 144",
	     expect="filled 144/144 L of gt6:potion.poison.long.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.poison.long.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.fireresistance.lingering 144",
	     expect="filled 144/144 L of gt6:potion.fireresistance.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.fireresistance.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.fireresistance.long.lingering 144",
	     expect="filled 144/144 L of gt6:potion.fireresistance.long.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.fireresistance.long.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.nightvision.lingering 144",
	     expect="filled 144/144 L of gt6:potion.nightvision.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.nightvision.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.nightvision.long.lingering 144",
	     expect="filled 144/144 L of gt6:potion.nightvision.long.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.nightvision.long.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.weakness.lingering 144",
	     expect="filled 144/144 L of gt6:potion.weakness.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.weakness.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.weakness.long.lingering 144",
	     expect="filled 144/144 L of gt6:potion.weakness.long.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.weakness.long.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.slowness.lingering 144",
	     expect="filled 144/144 L of gt6:potion.slowness.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.slowness.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.slowness.long.lingering 144",
	     expect="filled 144/144 L of gt6:potion.slowness.long.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.slowness.long.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.waterbreathing.lingering 144",
	     expect="filled 144/144 L of gt6:potion.waterbreathing.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.waterbreathing.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.waterbreathing.long.lingering 144",
	     expect="filled 144/144 L of gt6:potion.waterbreathing.long.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.waterbreathing.long.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.invisibility.lingering 144",
	     expect="filled 144/144 L of gt6:potion.invisibility.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.invisibility.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:potion.invisibility.long.lingering 144",
	     expect="filled 144/144 L of gt6:potion.invisibility.long.lingering (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:potion.invisibility.long.lingering (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:riverwater 250",
	     expect="filled 250/250 L of gt6:riverwater (ACCEPTED)"),
	Step(f"gt6tank stat {BARREL}",
	     expect="250/64000 L of gt6:riverwater, temperature 273 K"),
	Step(f"gt6tank draw {BARREL} 250",
	     expect="drawn 250/250 L of gt6:riverwater (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:ic2distilledwater 144",
	     expect="filled 144/144 L of gt6:ic2distilledwater (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:ic2distilledwater (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:goldencarrotjuice 144",
	     expect="filled 144/144 L of gt6:goldencarrotjuice (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:goldencarrotjuice (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:holywater 144",
	     expect="filled 144/144 L of gt6:holywater (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:holywater (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:rottendrink 250",
	     expect="filled 250/250 L of gt6:rottendrink (ACCEPTED)"),
	Step(f"gt6tank stat {BARREL}",
	     expect="250/64000 L of gt6:rottendrink, temperature 275 K"),
	Step(f"gt6tank draw {BARREL} 250",
	     expect="drawn 250/250 L of gt6:rottendrink (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:poison 144",
	     expect="filled 144/144 L of gt6:poison (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:poison (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:chocolatemilk 144",
	     expect="filled 144/144 L of gt6:chocolatemilk (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:chocolatemilk (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:medicine.heal 144",
	     expect="filled 144/144 L of gt6:medicine.heal (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:medicine.heal (ACCEPTED)"),
	Step(f"gt6tank fill {BARREL} gt6:medicine.laxative 144",
	     expect="filled 144/144 L of gt6:medicine.laxative (ACCEPTED)"),
	Step(f"gt6tank draw {BARREL} 144",
	     expect="drawn 144/144 L of gt6:medicine.laxative (ACCEPTED)"),
]
phase("D: teardown — the explicit restore over the band (the pass-open bbox is the backstop)")
steps += [
    Step(f"fill 402 62 18 406 66 22 air", expect="filled"),
    Step("time query daytime", expect="The time is"),
]

CHAIN = Chain(
    name="food-drink",
    slug="fooddrink",
    sites=gt6world.declare_sites(BARREL_SITE),
    preferred_ports=(26113, 26123),      # this card's pinned rcon/query pair (the 2610x segment, after extruder 26112/26122)
    steps=steps,
)


if __name__ == "__main__":
    main(CHAIN)
