# 1.21.1 NeoForge 节点参数（加载机制见 ../1.20.1-forge/gradle.properties 注释）。
# deps.neoforge = 21.1 线最新稳定（maven.neoforged.net releases，2026-09-03 查证：21.1.249）。
# deps.fml = javafml 语言加载器版本（mods.toml loaderVersion "[2,)"，0.7 官方模板 1.20.5+ 线钉值）。
# deps.neoforge_range = mods.toml 依赖 versionRange（neoforge 21 大线）。
deps.minecraft=1.21.1
deps.neoforge=21.1.249
deps.fml=2
deps.neoforge_range=[21,)
