package gregtech6.jei;

import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;

import mezz.jei.api.IModPlugin;
import mezz.jei.api.JeiPlugin;
import mezz.jei.api.registration.IRecipeRegistration;

import gregtech6.registry.GTMultiBlocks;

/**
 * The JEI integration plugin (task p12-jei-integration, ADR 2026-09-02-p12-jei-dependency) —
 * the first third-party mod integration of the port.
 *
 * <p>Detection contract: JEI discovers plugins by scanning for the {@link JeiPlugin} annotation
 * and instantiating the class through its NO-ARG constructor ("All {@code IModPlugin} must have
 * this annotation and a constructor with no arguments", JeiPlugin.java — JEI 1.20.1 CommonApi);
 * the implicit default constructor satisfies the second half. Same shape as the GTCEu Modern
 * precedent (GTJEIPlugin.java:43-44: {@code @JeiPlugin} + {@code implements IModPlugin}).
 *
 * <p>Self-contained by card ruling: this class touches nothing in {@code GT6Mod} /
 * {@code GTModBusListener} (frozen) — JEI loads it on its own when present. JEI is a
 * client-only mod, so on a dedicated server the JEI jar sits dormant on the classpath and this
 * class is never loaded (harmless-impl face, runServer gate).
 *
 * <p>Scope ruling (card "不做" ①②): NO custom {@code IRecipeCategory} and NO coke-oven recipe
 * category bridge — the only content face is the built-in ingredient info page
 * ({@code IRecipeRegistration.addIngredientInfo}, since JEI 7.6.4: auto line-wrap and
 * pagination, IRecipeRegistration.java:90-92 {@code addIngredientInfo(ItemLike, Component...)})
 * hung on the coke oven controller item, with the text living on the lang side
 * ({@link #INFO_KEY_COKE_OVEN}, generated by the GT6EnUs provider — the hand-written-JSON
 * red line does not apply here).
 */
@JeiPlugin
public class GT6JeiPlugin implements IModPlugin {

	/** Stable plugin uid path — the offline test pins both halves against drift. */
	public static final String PLUGIN_UID_PATH = "jei_plugin";

	/**
	 * The coke oven structure info-page lang key — the single reconciliation seam between this
	 * plugin (consumer) and the GT6EnUs datagen provider (producer).
	 */
	public static final String INFO_KEY_COKE_OVEN = "gt6.jei.info.multiblock_coke_oven";

	/** Stable plugin uid — one constant instance, the offline test pins it against drift. */
	public static final ResourceLocation PLUGIN_UID = new ResourceLocation("gt6", PLUGIN_UID_PATH);

	@Override
	public ResourceLocation getPluginUid() {
		return PLUGIN_UID;
	}

	@Override
	public void registerRecipes(IRecipeRegistration registration) {
		registration.addIngredientInfo(GTMultiBlocks.COKE_OVEN_ITEM.get(),
				Component.translatable(INFO_KEY_COKE_OVEN));
	}
}
