package gregtech6.jei;

import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;

import mezz.jei.api.IModPlugin;
import mezz.jei.api.JeiPlugin;
import mezz.jei.api.registration.IRecipeRegistration;
import mezz.jei.api.registration.IVanillaCategoryExtensionRegistration;

import gregtech6.items.tools.GT6MaterialToolRecipe;
import gregtech6.registry.GTMultiBlocks;

/**
 * The JEI integration plugin (task p12-jei-integration, ADR 2026-09-02-p12-jei-dependency) —
 * the first third-party mod integration of the port.
 *
 * <p>Detection contract: JEI discovers plugins by scanning for the {@link JeiPlugin} annotation
 * and instantiating the class through its NO-ARG constructor ("All {@code IModPlugin} must have
 * this annotation and a constructor with no arguments", JeiPlugin.java — JEI 1.20.1 CommonApi);
 * the implicit default constructor satisfies the second half. Same shape as the GTCEu Modern
 * precedent (GTJEIPlugin.java:43-44: {@code @JeiPlugin} + {@code implements IModPlugin}).
 *
 * <p>Dual-node wiring (task p15-jei-dual-wiring): this single shared source compiles against
 * both pinned JEI stacks — 1.20.1 Forge (mezz.jei:jei-1.20.1-{common-api,forge-api}:15.56.0.205,
 * modCompileOnly/modRuntimeOnly, mdk/build.forge.gradle.kts) and 1.21.1 NeoForge
 * (mezz.jei:jei-1.21.1-{common-api,neoforge-api}:19.52.0.422, plain compileOnly/runtimeOnly —
 * the moddev plugin registers no mod* remapping configurations, live configuration probe
 * 2026-09-04). javap on the two generations shows the consumed faces identical ({@code IModPlugin}
 * 20 methods with {@code getPluginUid() : ResourceLocation} abstract, {@code IRecipeRegistration}
 * including {@code addIngredientInfo(ItemLike, Component...)}), so the plugin faces stay
 * fork-free; the one fork in this file is the extension registration call — the two JEI
 * generations renamed the crafting-category extension API (15.x
 * {@code addCategoryExtension} / 19.x {@code addExtension}, see
 * {@link #registerVanillaCategoryExtensions}). The class stays strictly on the
 * loader-neutral common API — the platform packages ({@code mezz.jei.api.forge} /
 * {@code mezz.jei.api.neoforge}) are deliberately untouched, pinned by the GT6JeiPluginTest
 * bytecode guard (noPlatformSpecificJeiApiInBytecode).
 *
 * <p>Self-contained by card ruling: this class touches nothing in {@code GT6Mod} /
 * {@code GTModBusListener} (frozen) — JEI loads it on its own when present. JEI is a
 * client-only mod, so on a dedicated server the JEI jar sits dormant on the classpath and this
 * class is never loaded (harmless-impl face, runServer gate).
 *
 * <p>Scope ruling (card "不做" ①②): NO custom {@code IRecipeCategory} and NO coke-oven recipe
 * category bridge — the content faces are the built-in ingredient info page
 * ({@code IRecipeRegistration.addIngredientInfo}, since JEI 7.6.4: auto line-wrap and
 * pagination, IRecipeRegistration.java:90-92 {@code addIngredientInfo(ItemLike, Component...)})
 * hung on the coke oven controller item, with the text living on the lang side
 * ({@link #INFO_KEY_COKE_OVEN}, generated by the GT6EnUs provider — the hand-written-JSON
 * red line does not apply here), and (task r3-jei-tool-output-tint) the vanilla crafting
 * category EXTENSION for {@code gt6:material_tool} rows — an extension, not a custom
 * category: the recipes stay in the player's familiar crafting tab with unchanged search
 * behaviour, only the output slot gains the per-material representative stack (the b'
 * ruling, research.issues-r3-tool-jei).
 */
@JeiPlugin
public class GT6JeiPlugin implements IModPlugin {

	/** Stable plugin uid path — the offline test pins both halves against drift. */
	public static final String PLUGIN_UID_PATH = "jei_plugin";

	/**
	 * The coke oven structure info-page lang key — the single reconciliation seam between this
	 * plugin (consumer) and the GT6EnUs datagen provider (producer).
	 */
	public static final String INFO_KEY_COKE_OVEN = "gt6.jei.info.multiblock_coke_oven";

	/** Stable plugin uid — one constant instance, the offline test pins it against drift. */
	public static final ResourceLocation PLUGIN_UID = new ResourceLocation("gt6", PLUGIN_UID_PATH);

	@Override
	public ResourceLocation getPluginUid() {
		return PLUGIN_UID;
	}

	@Override
	public void registerRecipes(IRecipeRegistration registration) {
		registration.addIngredientInfo(GTMultiBlocks.COKE_OVEN_ITEM.get(),
				Component.translatable(INFO_KEY_COKE_OVEN));
	}

	/**
	 * The gt6:material_tool display seam (task r3-jei-tool-output-tint, GitHub #6 round 3):
	 * without an extension JEI renders the crafting category's output slot from the bare
	 * {@code getResultItem} stack, so every material row shows the Steel fallback colour
	 * while real crafts stamp the identity. The registered {@link GT6MaterialToolJeiExtension}
	 * swaps in the row's stamped representative stack — same category, same search
	 * behaviour, zero crafting-semantics change. The registration call itself is the file's
	 * one leg fork: the two JEI generations renamed the extension API (see the extension
	 * class javadoc for the lineage).
	 */
	@Override
	public void registerVanillaCategoryExtensions(IVanillaCategoryExtensionRegistration registration) {
		//? if forge {
		// 15.x: the extension wraps the recipe instance (IExtendableRecipeCategory.addCategoryExtension).
		registration.getCraftingCategory().addCategoryExtension(GT6MaterialToolRecipe.class, GT6MaterialToolJeiExtension::new);
		//?} else {
		/*// 19.x: a stateless singleton receives the recipe in each call (since 16.0.0).
		registration.getCraftingCategory().addExtension(GT6MaterialToolRecipe.class, GT6MaterialToolJeiExtension.INSTANCE);
		*///?}
	}
}
