package gregtech6.registry;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.List;

import org.junit.jupiter.api.Test;

import gregtech6.tileentity.GTOfflineTestBase;

/**
 * The written-book pins (task p35-books-written, ACCEPTANCE "文本逐本对照抽样钉"): the
 * committed {@link GT6BookText} distillate is pinned against the upstream anchor
 * (loaders/b/Loader_Books.java) — per book: path/upstream-line/title/author/page-count +
 * a whole-book SHA-256 (title+author+every raw page, the mechanical total-coverage pin)
 * + THREE sampled pages verbatim (first/middle/last, the readable face of the pin).
 * The anchor table was generated by running extract_books.extract against the upstream
 * file (the single-source discipline — no hand transcription), then frozen as literals.
 *
 * <p>Converter pins: the UT.java:622-628 page semantics (length < 256 kept, '¶' -> \n)
 * and the 32-char title cap (the vanilla WrittenBookItem.makeSureTagIsValid bound, both
 * legs) over synthetic rows. CUT declaration: the five non-shipped books stay absent as
 * an executable assertion. The registration walk: ITEMS_BY_PATH follows BOOKS one-to-one.
 */
public class GT6BooksWrittenPinTest extends GTOfflineTestBase {

	/** The upstream anchor: path, Loader_Books line, title, author, page count, whole-book sha256, 3 sampled pages. */
	private static final String[][] ANCHOR = {
			{"manual_printer", "72", "Scanner & Printer Manual", "GregTech Electrics", "7", "6a81be75f64b7d79a0bff77c3def0cf273cdd9af19cc5be1a732238756c0d265",
				"Congratulations on your acquisition of a new Scanner and/or Printer. You will find this Manual that you received with your purchase very useful. Just remember that if you lose it, you can just let the Printer create a new one.",
				"Now you need to refill your Printers Ink reserves, depending on what Job you want to do with it. It only accepts the Chemical Dyes for this purpose. Black = Text, CMYK for Images, Blue or White for Blueprints.",
				"The Printer can do a few more print jobs than just canvas and books. NEI will help you with all the possible Recipes."},
			{"manual_steam", "82", "Steam Manual", "GregTech Thermodynamics", "10", "8d26662e7b5d5b012fea6319676566eaa7f020a959464ddc4320c95ba8e1ccda",
				"This Manual is about the proper operation of a Boiler, in order to not blow yourself up. And yes there are many people who get blown up by improper operation of a Boiler.",
				"If a Boiler stores too much Heat without being able to convert Water into Steam, then it will simply melt and break, leaving you with a giant mess.",
				"If the Engines are too Red then they will release the Steam and stop running (no Explosions, just a waste of Steam and a fizzing noise)."},
			{"manual_random", "95", "Tips & Tricks with GregTech Six", "Gregorius Techneticies", "13", "435deaa9f166372024f985b80113f289cde36ce09098e8d6e9e46d03122cf7a1",
				"This Book contains random Information that might be useful sometime. Read it whenever you have Issues. Maybe it has the Solution.",
				"GT6 Electric Power is widely compatible with all Mods that use the IC² API, such as:¶IC², IC²-Classic, IC²-Addons, Railcraft, Forestry and more!",
				"Space out Machines a little in order to be able to automate them later without causing a huge Clusterfuck. Always have enough space for 2 Blocks inbetween each Machine, if not 3! Disregard the eventual Loss of Power, it's not worth it."},
			{"manual_enchantments", "219", "The vexing World of Enchantments", "Evoker Number 42", "36", "d424ffa79a08a1cf959522c2030de8977f1b585a8048a7525ad8eea0b1251b65",
				"I cant believe how hard it is to find Information on these ancient Enchantments! But here I am, finally having collected everything there is to know about this Magic!",
				"Fortune¶===================¶Levels 1 to 3+¶Increases the amount of drops you get from Blocks. It may increase the total drops themselves or the chance that you get some rare drop at all. Works on Ores, Crops, Gravel, and Glowstone.",
				"Unbreaking¶===================¶Levels 1 to 3+¶Tools with this Enchantment on average last longer by +100% per Level. Armors will only last +25%, +34% or +43% longer. Tool Materials never have this Enchantment because it would be pointless."},
			{"manual_hunting_creeper", "261", "Hunting Guide for Creepers", "Alex Grylls, Survival Specialist", "9", "478ac6fa6ca86ac201bd6b59676febf158aaf15ceca3fbab9198f9b432bc1e5d",
				"Hi, I'm Alex Grylls, Adventurer and experienced Hunter of the several Mobs you encounter in our World. In this Guide I will explain you easy Methods to hunt for wild Mobs in their natural Habitats.",
				"Creepers¶===================¶Water is also a good place to melee a Creeper, as knockback will get it out of explosion Range, and even if it explodes it will not cause Damage to the ground, due to the Water absorbing the shock.",
				"Creepers¶===================¶Last but not least, you can always just drop Water between you and the Creeper, it will slow it down considerably and if its about to explode anyways, then it won't damage the Terrain."},
			{"manual_hunting_skeleton", "272", "Hunting Guide for Skeletons", "Alex Grylls, Survival Specialist", "28", "c31446a1af3026a8b5a0f0b15d0093f17aaf1d127b35c94b04cab66352b9bdc8",
				"Hi, I'm Alex Grylls, Adventurer and experienced Hunter of the several Mobs you encounter in our World. In this Guide I will explain you easy Methods to hunt for wild Mobs in their natural Habitats.",
				"Skeletons¶===================¶It is always a good Idea to just make Skeletons attack each other or other Mobs in order to make the attacked Mob angry at them (instead of you), causing them to kill each other.",
				"Wither Skeletons¶===================¶The Heads, which are dropped by every 40th Wither Skeleton, can be used to summon the Wither, but the Wither is being talked about in another Book."},
			{"manual_hunting_zombie", "302", "Hunting Guide for Zombies", "Alex Grylls, Survival Specialist", "38", "376615b4d333e6edc9b1137f21bd5762c234469e911f50f7f134bb8068f4907a",
				"Hi, I'm Alex Grylls, Adventurer and experienced Hunter of the several Mobs you encounter in our World. In this Guide I will explain you easy Methods to hunt for wild Mobs in their natural Habitats.",
				"Chicken Jockeys¶===================¶Shoot the Chicken, yes get rid of it as fast as possible, you won't be able to Melee it as the Zombie is in the way, but you can try to shoot it!",
				"Zombie Villagers¶===================¶So, now that you got the Villager into a Cage, you can heal them. Once you have done that, transport the Villager somewhere else, maybe with Rails and Minecarts."},
			{"manual_hunting_spider", "342", "Hunting Guide for Spiders", "Alex Grylls, Survival Specialist", "14", "2dc24be4c3ba10861e7fc979ab8765794d46b412addb47f1ad1a183ed3d8853c",
				"Hi, I'm Alex Grylls, Adventurer and experienced Hunter of the several Mobs you encounter in our World. In this Guide I will explain you easy Methods to hunt for wild Mobs in their natural Habitats.",
				"Spiders¶===================¶Running is the best thing to do when fighting Spiders, not running away, I mean running at them or keeping a safe distance during combat. Spiders are immune to Poison, so splashing them with it isn't effective at all.",
				"Cave Spiders¶===================¶Due to them being poisonous, Milk or any sort of Antidote Pill are useful Items to have on your Hotbar. Also hiding from them by closing off Paths is very needed sometimes."},
			{"manual_hunting_end", "358", "Hunting Guide for the End", "Alex Grylls, Survival Specialist", "17", "2e9b6d5418a9a471db66e08cd35bd5d8246996a0e23280d4c2b6401ee36bfab1",
				"Hi, I'm Alex Grylls, Adventurer and experienced Hunter of the several Mobs you encounter in our World. In this Guide I will explain you easy Methods to hunt for wild Mobs in their natural Habitats.",
				"Endermen¶===================¶If you encounter an angry Enderman, then try to run into the closest Forest, the low Trees are perfect hiding Spots, and they cant teleport to you if they are too close to you already.",
				"Ender Dragon¶===================¶During the Fight it can happen that you stare at Endermen by accident, in order to prevent that you could either wear a Pumpkin as Hat and press F1, or just try to only look at a slight upwards angle."},
			{"manual_hunting_blaze", "377", "Hunting Guide for Blazes and Ghasts", "Alex Grylls, Survival Specialist", "16", "83558de9eb1dbe002659d9ecc9231aaaa1e4163a3cc3d958d9f38818cc687652",
				"Hi, I'm Alex Grylls, Adventurer and experienced Hunter of the several Mobs you encounter in our World. In this Guide I will explain you easy Methods to hunt for wild Mobs in their natural Habitats.",
				"Ghasts¶===================¶Ghasts, flying, ghost alike, crying Tentacle Monsters with explosive Projectiles. Their Tears are hard to get due to them being airborne and the Nether being all like 'The Floor is Lava!'.",
				"Ghasts¶===================¶Ghasts are the normal kind of Mob, they are neither Undead nor Spiders, there is no special Enchant against them, and Potions work normally on them."},
			{"manual_hunting_witch", "395", "Hunting Guide for Witches", "Alex Grylls, Survival Specialist", "7", "f3b5211e1ce8a990bb174bc4b50e0e02feb4fc82a6d1df4f958492141e1a8e97",
				"Hi, I'm Alex Grylls, Adventurer and experienced Hunter of the several Mobs you encounter in our World. In this Guide I will explain you easy Methods to hunt for wild Mobs in their natural Habitats.",
				"Witches¶===================¶Bow and Arrow are ofcourse a good option, but if you have to melee then do it fast and run straight at the Witch to hit them. This will cause the Witch to try healing themself instead of attacking you.",
				"Witches¶===================¶Witches drop Empty Bottles, Sticks, Redstone, Glowstone, Sugar, Spider Eyes, Gunpowder and Potions. This makes them a valuable Mob to farm and also a way to get Glowstone and Potions without the Nether."},
			{"manual_tools", "518", "Tool Index", "GITF (Gregorius Industrial Tool Factory)", "43", "3334e13ae646fd27e68a52d40f8d851eae45d9e96e96ae65b514220b49bb6b4d",
				"This Manual is about common and uncommon Tools and how to use them. It contains a List of every normal Tool that you might not know the true purpose of.",
				"Wrenches¶===================¶Adjusts the primary Facing of most Machines, sometimes it can be used to toggle Modes aswell.",
				"Pocket Multitool¶===================¶A Multi-Tool that can be switched to the most common purposes. See it as a Swiss Army Knife."},
			{"manual_smeltery", "565", "Smelting Crucible Manual", "GMWI (Gregorius Metal Working Industries)", "42", "bcb321ffeb77d7d1a6bf4802870b08b084254e0a5c74449cfbc0509da8d431ff",
				"This is the Manual of the Smelting Crucible and related Objects. It will explain how to use the Smelting Crucible and the Molds properly, so that you can start smelting things which cannot me molten inside a regular Furnace.",
				"Item Casing¶===================¶XXXOX¶XXXOX¶XXXOX¶OOOOX¶XXXOO¶===================¶0.500 Units required",
				"Builder's Wand¶===================¶OOXOO¶XXXXX¶OXXXO¶OXOXO¶OOOOO¶===================¶1.000 Units required"},
			{"manual_extenders", "600", "Extenders & Filters", "GAD (Gregorius Automation Distributions)", "13", "f575e1b31e54721e15ab1a0bb48c2fce27ababe99c89dc5f92e751b6dfbf77d5",
				"This Manual covers Extenders as well as Filters. It will explain the usage of those Devices in Detail, so that you can use them easily. ",
				"This means that if you have Input and Output on the same Side of the TileEntity you attach it to, that you can redirect the Output into one Direction using the Secondary Facing, while the Neutral Facings fill the TileEntity on the Main Facing.",
				"They do NOT do anything by themselves at all, they just sit there pretending to be whatever TileEntity you attached them to. So do not expect them to pull or push Items around or something dumb like that."},
			{"manual_reactors", "618", "Fission Reactor Manual", "Apature Atomics", "133", "ea4072c1a06b6a6301e34d0339632ad73e08a8ae439ce86c6e02d7fbfea826e6",
				"¶¶===================¶Introduction and Safety Instructions¶===================¶",
				"It also increases the self and emission stat which is really advantageous in stable reactors, as it means more Neutrons and therefore more efficiency.",
				"Setting the geiger counter sensor to hexadecimal mode is useful when trying to control neutron counts greater than 9_999. In hexadecimal mode you can compare up to 65_535 neutrons."},
		};

	@Test
	public void booksCensusPinsTheUpstreamAnchor() throws Exception {
		assertEquals(ANCHOR.length, GT6BookText.BOOKS.size(), "the 15-book static scope (the coordinator-approved face)");
		MessageDigest tDigest = MessageDigest.getInstance("SHA-256");
		for (int i = 0; i < ANCHOR.length; i++) {
			GT6BookText.BookText tRow = GT6BookText.BOOKS.get(i);
			String[] tPin = ANCHOR[i];
			// tPin[1] = the upstream Loader_Books line, the GT6BookText comment provenance face
			assertEquals(tPin[0], tRow.path(), "row " + i + " path (order pinned)");
			assertEquals(tPin[2], tRow.title(), "row " + i + " title");
			assertEquals(tPin[3], tRow.author(), "row " + i + " author");
			assertEquals(Integer.parseInt(tPin[4]), tRow.pages().size(), "row " + i + " page count");
			// the whole-book face: title + author + every raw page, the mechanical total pin
			tDigest.reset();
			String tComposite = tRow.title() + "\u0000" + tRow.author() + "\u0000" + String.join("\u0000", tRow.pages());
			StringBuilder tHex = new StringBuilder();
			for (byte tByte : tDigest.digest(tComposite.getBytes(StandardCharsets.UTF_8))) {
				tHex.append(String.format("%02x", tByte));
			}
			assertEquals(tPin[5], tHex.toString(), "row " + i + " whole-book sha256");
		}
	}

	@Test
	public void sampledPagesMatchTheAnchorFace() {
		for (int i = 0; i < ANCHOR.length; i++) {
			GT6BookText.BookText tRow = GT6BookText.BOOKS.get(i);
			int tCount = tRow.pages().size();
			// first / middle / last — the >= 3 sampled content pins per book
			assertEquals(ANCHOR[i][6], tRow.pages().get(0), tRow.path() + " first page");
			assertEquals(ANCHOR[i][7], tRow.pages().get(tCount / 2), tRow.path() + " middle page");
			assertEquals(ANCHOR[i][8], tRow.pages().get(tCount - 1), tRow.path() + " last page");
		}
	}

	@Test
	public void converterPinsTheUpstreamPageSemantics() {
		// UT.java:622-628 verbatim: length < 256 kept (255 in, 256 out), '¶' -> '\n'
		String tKeep = "x".repeat(255);
		String tDrop = "x".repeat(256);
		GT6BookText.BookText tRow = new GT6BookText.BookText("synthetic", "T", "A",
				List.of("first\u00b6second", tKeep, tDrop, "last"));
		List<String> tPages = GT6Books.convertPages(tRow);
		assertEquals(List.of("first\nsecond", tKeep, "last"), tPages, "the drop bound is < 256 and the marker folds to a newline");
	}

	@Test
	public void titleCapIsTheVanillaWrittenBookBound() {
		// 1.20.1 WrittenBookItem.makeSureTagIsValid + 1.21.1 WrittenBookContent CODEC both bind 0..32
		assertEquals("x".repeat(32), GT6Books.convertTitle(new GT6BookText.BookText("s", "x".repeat(32), "A", List.of("p"))));
		assertEquals("y".repeat(32), GT6Books.convertTitle(new GT6BookText.BookText("s", "y".repeat(33), "A", List.of("p"))));
		// the one over-bound row: the blaze guide title truncates uniformly on both legs
		GT6BookText.BookText tBlaze = GT6BookText.BOOKS.stream()
				.filter(aRow -> aRow.path().equals("manual_hunting_blaze")).findFirst().orElseThrow();
		assertEquals(35, tBlaze.title().length(), "the raw upstream title exceeds the 32-char bound");
		assertEquals(tBlaze.title().substring(0, 32), GT6Books.convertTitle(tBlaze));
	}

	@Test
	public void cutBooksStayAbsent() {
		// the CUT declaration as an executable assertion (the generator docstring carries the evidence)
		for (String tCut : new String[] {"manual_punch_cards", "manual_microwave", "manual_portal_tf", "manual_alloys", "manual_elements"}) {
			assertTrue(GT6BookText.BOOKS.stream().noneMatch(aRow -> tCut.equals(aRow.path())),
					"the CUT book '" + tCut + "' stays unshipped");
			assertFalse(GT6Books.ITEMS_BY_PATH.containsKey(tCut), "the CUT book '" + tCut + "' stays unregistered");
		}
	}

	@Test
	public void noCommittedPageHitsTheDropBound() {
		// the generator invariant: every static page survives the UT.java:623 filter unchanged
		for (GT6BookText.BookText tRow : GT6BookText.BOOKS) {
			for (int i = 0; i < tRow.pages().size(); i++) {
				assertTrue(tRow.pages().get(i).length() < 256, tRow.path() + " page " + i + " stays under the drop bound");
			}
		}
	}

	@Test
	public void itemsWalkTheRowsOneToOne() {
		assertEquals(GT6BookText.BOOKS.size(), GT6Books.ITEMS_BY_PATH.size(), "one item per book row");
		int i = 0;
		for (String tPath : GT6Books.ITEMS_BY_PATH.keySet()) {
			assertEquals(GT6BookText.BOOKS.get(i).path(), tPath, "item " + i + " follows the row order");
			i++;
		}
	}
}
